## Relational Diagram

*   Please click here: https://drive.google.com/file/d/1vhwxF_E1BflRkVSjNsjo3Oib3U1GsRK-/view?usp=sharing

## Sampled Client (ID: I8LN9Q)

*   this client has 4 accounts (**I8LN9QE**: Margin Long in CAD / **I8LN9QF**: Margin Long in USD / **I8LN9QS**: Cash in CAD / **I8LN9QW**: Cash in CAD)
*   We will use this sampled client to see the column details or data structures in SP100, SP200, SP399, and BV399 datasets.

**First, let's look at the general profile information for this client, the following 103 columns are extracted from cust_acct_detail.csv**

(376, 103)

        account_rap_code  acct_account_class acct_client  acct_closing_date  acct_closure_reason  acct_commission_acct_id acct_consol_eligible_sw acct_cr_int_method  acct_credit_limit_type acct_currency  acct_date_last_traded  acct_deceased_fair_mkt_val  acct_div_conf_id acct_dr_int_method acct_fin_transfer_sss_id acct_fin_transfer_sss_locn acct_function_code  acct_guaranteegtor_type  acct_id acct_internal_cde4 acct_language acct_lvlord acct_mailing_list_id acct_multiple_name_sw  acct_open_date  acct_options_trading_type acct_registration_instruct acct_representative acct_sharhldr_instr_sw acct_special_tag  acct_target_gg                        acct_title acct_tms_eligible_sw acct_type  asc_1_resp_plan_types asc_2_product_type asc_3_managed_type asc_6_client_category  asc_9_special_process broker_code citizenship  class_id  client_access_group client_annual_gross_inc  client_birth_date client_company_ctrl_sw  client_credit_card_nbr_1  client_credit_card_nbr_2  client_credit_card_nbr_3  client_credit_check_sw  client_deceased_date client_discretionary_sw client_education_level client_extract_eligible client_inv_exp_lvl  client_inv_knowledge_lvl client_inv_objective_1 client_inv_objective_2 client_inv_objective_4 client_inv_objective_5  client_inv_objective_6 client_marital_status client_name_salutation client_net_worth  client_non_residence_code client_occupation_desc client_rep_priority client_residence client_residence_region client_risk_tolerance client_sex  client_tax_recip_type client_type  consent_pay_ind  contract_type  credit_card_no2  credit_card_no3  e_delivery_consent   file_date  individual_taxpayer           ivt_obj_cde  last_update_date  last_update_date2      misc_2  non_obj_ben_own non_plan_bv_str  non_res_start_date  nra_tax_pool  obj_ben_own  received_instr retail_plan  retail_plan_eff_date  retail_plan_end_date  retail_plan_grandfatherd  retail_plan_num_benef  retail_plan_original_date retail_plan_pledge_sw  retail_plan_resp_family_i  retail_plan_resp_specmn_p        risk_tolerance spoken_lang us_person_ind  us_recipient_type
6554813                E                  40      I8LN9Q                  0                  NaN                      NaN                       Y                  P                       0           CAD               20190614                         0.0                 0                  P                                                                                               3  I8LN9QE                  D            E           CL                 0000                              20161229                          0                         0                 0RC2                      N                              NaN  MRS.                                                N       MRL                      0                  0                  0                     0                      0       ALIGN         CAN       NaN                  NaN                   100K                1959                      N                       NaN                       NaN                       NaN                     NaN                     0                       N                                       Y                                                 2.0                   G.99                                                                                          NaN                     M                   MRS.            200K+                          0   BOOKKEEPER                             N              CAN                  ON      M.60H.40                      F                      1         *                  0           17.0              NaN              NaN                   0  2019-08-12                  NaN  G99                           20190315           20161229                            0               V                   0           2.0            1               1                                 0                     0                       NaN                    NaN                          0                                              NaN                        NaN  H40Q60                       ENG             N               16.0
6554816                F                  40      I8LN9Q                  0                  NaN                      NaN                       Y                  P                       0           USD               20181219                         0.0                 0                  P                                                                                               2  I8LN9QF                  D            E           CL                 0000                              20161229                          0                         0                 0RC2                      N                              3.0  MRS.                                                N       MRL                      0                  0                  0                     0                      0       ALIGN         CAN       NaN                  NaN                   100K                1959                      N                       NaN                       NaN                       NaN                     NaN                     0                       N                                       Y                                                 2.0                   G.99                                                                                          NaN                     M                   MRS.            200K+                          0   BOOKKEEPER                             N              CAN                  ON      M.60H.40                      F                      1         *                  0           17.0              NaN              NaN                   0  2019-08-12                  NaN  G99                           20190315           20161229                            0               V                   0           2.0            1               1                                 0                     0                       NaN                    NaN                          0                                              NaN                        NaN  H40Q60                       ENG             N               16.0
6554817                S                  38      I8LN9Q                  0                  NaN                      NaN                       Y                  5                       0           CAD               20190102                         0.0                 0                  R                                                                                               2  I8LN9QS                  D            E                              0000                              20161229                          0                         0                 0RC2                      N                              NaN  MRS.                                                N       CSH                      0                  0                  0                     0                      0       ALIGN         CAN       NaN                  NaN                   100K                1959                      N                       NaN                       NaN                       NaN                     NaN                     0                       N                                       Y                                                 2.0                   G.99                                                                                          NaN                     M                   MRS.            200K+                          0   BOOKKEEPER                             N              CAN                  ON      M.60H.40                      F                      1         *                  0           17.0              NaN              NaN                   0  2019-08-12                  NaN  G99                           20190315           20161229                            0                                   0           2.0            1               1          RS              20161229                     0                       0.0                    0.0                   20161229                     N                        0.0                        NaN  H40Q60                       ENG             N               16.0
6554844                W                  38      I8LN9Q                  0                  NaN                      NaN                       Y                  5                       0           CAD                      0                         0.0                 0                  R                                                                                               2  I8LN9QW                  D            E                              0000                              20161229                          0                         0                 0RC2                      N                              NaN  MRS.                                                N       CSH                      0                  0                  0                     0                      0       ALIGN         CAN       NaN                  NaN                   100K                1959                      N                       NaN                       NaN                       NaN                     NaN                     0                       N                                       Y                                                 2.0                   G.99                                                                                          NaN                     M                   MRS.            200K+                          0   BOOKKEEPER                             N              CAN                  ON      M.60H.40                      F                      1         *                  0           17.0              NaN              NaN                   0  2019-08-12                  NaN  G99                           20190806           20161229                            0                                   0           2.0            1               1          TF              20161229                     0                       0.0                    0.0                   20161229                     N                        0.0                        NaN  H40Q60                       ENG             N               16.0

# SP100 (RRWS ACCOUNT PROFILE)

1.   cust_sp100_address.csv
2.   cust_sp100_client.csv
3.   sp100_accounts.csv 
4.   sp100_clients.csv
5.   sp100_client_pension.csv

## cust_sp100_address.csv

      acct_rep account_id address_postal_code  file_date
50065     0RC2    I8LN9QE                 L4J 2019-03-29
50067     0RC2    I8LN9QF                 L4J 2019-03-29
50068     0RC2    I8LN9QS                 L4J 2019-03-29
50091     0RC2    I8LN9QW                 L4J 2019-03-29

## sp100_clients.csv

* 232786 rows and 20 columns
* 36991 clients
* 366 advisors
* trading dates range from 2018-08-13 to 2019-08-12         ---> 251 trading days

        birth_date client_id client_rep  file_date gender income inv_obj_1 inv_obj_2 inv_obj_3 inv_obj_4 inv_obj_5  inv_obj_6 language_cd net_worth  occupation postal_cd resident_cd risk_tolerance  seq_id updcode
19596         1959    I8LN9Q       0RC2 2018-09-07      F   100K      G.99       NaN       NaN       NaN       NaN        NaN           E     200K+  BOOKKEEPER       L4J          13       M.60H.40   16886       C
76775         1959    I8LN9Q       0RC2 2018-12-20      F   100K      G.99       NaN       NaN       NaN       NaN        NaN           E     200K+  BOOKKEEPER       L4J          13       M.60H.40   25101       C
106265        1959    I8LN9Q       0RC2 2019-02-20      F   100K      G.99       NaN       NaN       NaN       NaN        NaN           E     200K+  BOOKKEEPER       L4J          13       M.60H.40   10825       C
141385        1959    I8LN9Q       0RC2 2019-03-04      F   100K      G.99       NaN       NaN       NaN       NaN        NaN           E     200K+  BOOKKEEPER       L4J          13       M.60H.40    6646       C
185753        1959    I8LN9Q       0RC2 2019-03-15      F   100K      G.99       NaN       NaN       NaN       NaN        NaN           E     200K+  BOOKKEEPER       L4J          13       M.60H.40   26841       C

## cust_sp100_client.csv (similar to file cust_kyc_details.csv)

* 7122270 rows and 28 columns
* 33051 clients
* 81894 accounts
* 332 advisors
* trading dates range from 2019-03-29 to 2019-08-12       ---> 95 trading days

        acct_type acct_service_code acct_rep acct_currency acct_internal_cde4 acct_internal_cde5           ivt_obj_cde account_id        risk_tolerance retail_plan_pension_origin client_residence_region client_language client_intro_rep client_id client_risk_tolerance client_occupation_desc client_net_worth client_annual_gross_inc  client_birth_date client_inv_knowledge_lvl client_sex client_inv_objective_1 client_inv_objective_2 client_inv_objective_3 client_inv_objective_4 client_inv_objective_5 client_inv_objective_6  file_date
7096317       MRL      000000000000     0RC2           CAD                  D                  0  G99                     I8LN9QE  H40Q60                                                           ON                  E              0RC2    I8LN9Q  M.60H.40               BOOKKEEPER                      200K+                   100K                1959                        2          F                   G.99                                                                                                                    2019-08-12
7096319       MRL      000000000000     0RC2           USD                  D                  0  G99                     I8LN9QF  H40Q60                                                           ON                  E              0RC2    I8LN9Q  M.60H.40               BOOKKEEPER                      200K+                   100K                1959                        2          F                   G.99                                                                                                                    2019-08-12
7096320       CSH      000000000000     0RC2           CAD                  D                  0  G99                     I8LN9QS  H40Q60                                                           ON                  E              0RC2    I8LN9Q  M.60H.40               BOOKKEEPER                      200K+                   100K                1959                        2          F                   G.99                                                                                                                    2019-08-12
7096343       CSH      000000000000     0RC2           CAD                  D                  0  G99                     I8LN9QW  H40Q60                                                           ON                  E              0RC2    I8LN9Q  M.60H.40               BOOKKEEPER                      200K+                   100K                1959                        2          F                   G.99                                                                                                                    2019-08-12

## sp100_accounts.csv

RAP codes: https://drive.google.com/open?id=19p8dqqbeBNjPGLSwO_4SeXLV-1HsvI8l

Account_type mapping: https://drive.google.com/open?id=1Gd6wmVKD7--Wg8nLR1LM0qcl6MJqzjyB

* 626737 rows and 12 columns
* 36983 client
* 97200 accounts
* 366 advisors
* trading dates range from 2018-08-13 to 2019-08-12         ---> 252 trading days

       account_id acct_funds_cd acct_rep  acct_serv_cd    acct_type client_id  clnt_seq_id  close_date  file_date planning_code  seq_id updcode
429806    I8LN9QE             C     0RC2  000000000000  Margin Long    I8LN9Q        68729         NaN 2019-03-15           NaN   68729       C
429807    I8LN9QF             U     0RC2  000000000000  Margin Long    I8LN9Q        68730         NaN 2019-03-15           NaN   68730       C
429808    I8LN9QS             C     0RC2  000000000000         Cash    I8LN9Q        68731         NaN 2019-03-15           NaN   68731       C
624037    I8LN9QW             C     0RC2  000000000000         Cash    I8LN9Q         5353         NaN 2019-08-06           NaN    5353       C

## sp100_client_pension.csv

* 443279 rows and 5 columns
* 60656 accounts
* trading dates range from 2018-08-13 to 2019-08-12         ---> 252 trading days

       account_id  acct_seq_id  file_date pension_origin  seq_id
282237    I8LN9QS        68731 2019-03-15            NaN   42848
441013    I8LN9QW         5353 2019-08-06            NaN    4998

# SP200 (TRANSACTION DETAIL - POSITIONS)

1.   cust_sp200_trade.csv
2.   cust_sp200_transactions.csv
3.   sp200_position_details.csv
4.  sp200_position_multi_fill.csv
5.  sp200_position_trade_grp.csv

## cust_sp200_trade.csv

* 98666 rows and 29 columns
* 297 advisors
* 299 trading reps
* 24018 accounts in dataset
* trading dates range from 2019-03-29 to 2019-08-12         ---> 95 trading days

      acct_service_code acct_rep account_id                     ti_short_desc  ti_alternate_id   ti_cusip  tran_trading_gross_amt  tran_trading_total_qty  tran_trading_net_amt  tran_trading_comm_amt  tran_trading_fx_rate tran_trading_sp_tax_sw tran_trading_cancel_sw tran_trading_sav_plan_sts  tran_trading_process_date  tran_trading_trade_date  tran_trading_sett_date tran_trading_source  tran_trading_ds_ti_type tran_trading_prem_disc_cd tran_trading_type tran_trading_market tran_trading_net_currency  tran_trading_sub_account  tran_trading_off_sub_act tran_trading_currency tran_trading_rep tran_trading_ti_symbol  file_date
57858      000000000000     0RC2    I8LN9QE  CANNTRUST HOLDINGS INC            14439H           137800207                 32900.0                  5000.0               33025.0                  125.0                   0.0                      N                      N                                             20190614                 20190614                20190618     097750                               315                                         AB               T                            CAD                         0                         0                   CAD             0RC2           TRST         2019-06-14

## cust_sp200_transactions

* 1596651 rows and 18 columns
* 322 advisors
* 59624 accounts
* trading dates range from 2019-03-29 to 2019-08-12         ---> 95 trading days

        acct_service_code acct_rep account_id  ti_alternate_id   ti_cusip                   ti_symbol  tran_gross_amt  tran_settlement_date  tran_trade_date  tran_qty  tran_amount_2             tran_user_description tran_currency  tran_process_date tran_entry_description tran_type tran_type_of_amount_2  file_date
307938       000000000000     0RC2    I8LN9QE  118224           136069101  CM                                -1176.00              20190429         20190429     840.0            0.0  CDN IMPERIAL BK COMMERCE                   CAD           20190429              DIV             DIV                       2019-04-29
354583       000000000000     0RC2    I8LN9QE  671835           891160509  TD                                 -925.00              20190430         20190430    1250.0            0.0  TORONTO DOMINION BANK                      CAD           20190430              DIV             DIV                       2019-04-30
546323       000000000000     0RC2    I8LN9QE  033740           037833100  AAPL                                -82.65              20190516         20190516      80.0            0.0  APPLE INC                                  CAD           20190516              DIV             DIV                       2019-05-16
546324       000000000000     0RC2    I8LN9QE  033740           037833100  AAPL                                 12.40              20190516         20190516      80.0            0.0  APPLE INC                                  CAD           20190516              WHTX02          CHG                       2019-05-16
586873       000000000000     0RC2    I8LN9QE  591131           780087102  RY                                 -943.50              20190524         20190524     925.0            0.0  ROYAL BANK OF CANADA                       CAD           20190524              DIV             DIV                       2019-05-24
1378527      000000000000     0RC2    I8LN9QE  CAD                                                             157.55              20190716         20190719       0.0            0.0  INTEREST TO JUL 16                         CAD           20190719              INT             INT                       2019-07-19
1427293      000000000000     0RC2    I8LN9QE  118224           136069101  CM                                -1176.00              20190729         20190729     840.0            0.0  CDN IMPERIAL BK COMMERCE                   CAD           20190729              DIV             DIV                       2019-07-29
1482468      000000000000     0RC2    I8LN9QE  671835           891160509  TD                                 -925.00              20190731         20190731    1250.0            0.0  TORONTO DOMINION BANK                      CAD           20190731              DIV             DIV                       2019-07-31
6957         000000000000     0RC2    I8LN9QF  01442A           G0176J109  ALLE                                  5.40              20190329         20190329     100.0            0.0  ALLEGION PLC                               USD           20190329              NRT             TAX                       2019-03-29
6958         000000000000     0RC2    I8LN9QF  01442A           G0176J109  ALLE                                -27.00              20190329         20190329     100.0            0.0  ALLEGION PLC                               USD           20190329              DIV             DIV                       2019-03-29
546326       000000000000     0RC2    I8LN9QF  033740           037833100  AAPL                               -163.24              20190516         20190516     212.0            0.0  APPLE INC                                  USD           20190516              DIV             DIV                       2019-05-16
546327       000000000000     0RC2    I8LN9QF  033740           037833100  AAPL                                 24.49              20190516         20190516     212.0            0.0  APPLE INC                                  USD           20190516              WHTX02          CHG                       2019-05-16
1096009      000000000000     0RC2    I8LN9QF  01442A           G0176J109  ALLE                                  5.40              20190628         20190628     100.0            0.0  ALLEGION PLC                               USD           20190628              NRT             TAX                       2019-06-28
1096010      000000000000     0RC2    I8LN9QF  01442A           G0176J109  ALLE                                -27.00              20190628         20190628     100.0            0.0  ALLEGION PLC                               USD           20190628              DIV             DIV                       2019-06-28
44387        000000000000     0RC2    I8LN9QS  075695           090697103  BIR                                -105.00              20190401         20190401    4000.0            0.0  BIRCHCLIFF ENERGY LTD                      CAD           20190401              DIV             DIV                       2019-04-01
307939       000000000000     0RC2    I8LN9QS  118224           136069101  CM                                 -826.00              20190429         20190429     590.0            0.0  CDN IMPERIAL BK COMMERCE                   CAD           20190429              DIV             DIV                       2019-04-29
643265       000000000000     0RC2    I8LN9QS  32082F           428304109  HEXO                                  0.00              20190531         20190531    1899.0            0.0  HEXO CORP                                  CAD           20190531              EXCH            *                         2019-05-31
643266       000000000000     0RC2    I8LN9QS  46811H           65250J108  HIP                                   0.00              20190531         20190531  -30000.0            0.0  NEWSTRIKE BRANDS LTD    *                  CAD           20190531              EXCH            *                         2019-05-31
766077       000000000000     0RC2    I8LN9QS  32082F           428304109  HEXO                                 -5.14              20190607         20190607       0.0            0.0  HEXO CORP                                  CAD           20190607              FRACT           JE                        2019-06-07
848475       000000000000     0RC2    I8LN9QS  CAD                                                               4.88              20190615         20190614       0.0            0.0  HST                                        CAD           20190614              HS3             CHG                       2019-06-14
848476       000000000000     0RC2    I8LN9QS  CAD                                                              37.50              20190615         20190614       0.0            0.0  CLIENT ADMIN FEE                           CAD           20190614              A01             CHG                       2019-06-14
1138553      000000000000     0RC2    I8LN9QS  075695           090697103  BIR                                -105.00              20190702         20190702    4000.0            0.0  BIRCHCLIFF ENERGY LTD                      CAD           20190702              DIV             DIV                       2019-07-02
1427294      000000000000     0RC2    I8LN9QS  118224           136069101  CM                                 -826.00              20190729         20190729     590.0            0.0  CDN IMPERIAL BK COMMERCE                   CAD           20190729              DIV             DIV                       2019-07-29
1096018      000000000000     0RC2    I8LN9QW  615691           82835P103  SVM                                 -11.41              20190628         20190628     700.0            0.0  SILVERCORP METALS INC                      CAD           20190628              DIV             DIV                       2019-06-28

## sp200_position_details

* 4253696 rows and 19 columns
* 67123 accounts
* trading dates range from 2018-08-13 to 2019-08-12         ---> 254 trading days

        account_id                description entry_type  file_date  is_exchange  is_reversal  is_trade  net_amount       price price_funds  process_date  quantity security_id  seq_id  trade_date  txn_bv_mv_ind  valid_amount  valid_quantity  value_date
62418      I8LN9QE                  APPLE INC        DIV 2018-08-16            0            0         0       65.13         NaN           C      20180816      80.0      033740    4974    20180816              0             1               0    20180816
89014      I8LN9QE       ROYAL BANK OF CANADA        DIV 2018-08-24            0            0         0      869.50         NaN           C      20180824     925.0      591131    6440    20180824              0             1               0    20180824
599662     I8LN9QE                    BCE INC       SELL 2018-10-10            0            0         1    69436.50   51.527040           C      20181010   -1350.0      070623    4541    20181010              0             1               1    20181012
599663     I8LN9QE     CANNTRUST HOLDINGS INC        BUY 2018-10-10            0            0         1   -71515.00   12.100000           C      20181010    5900.0      14439H    4542    20181010              0             1               1    20181012
654759     I8LN9QE                    BCE INC        DIV 2018-10-15            0            0         0     1019.25         NaN           C      20181015    1350.0      070623   39987    20181015              0             1               0    20181015
763196     I8LN9QE      TORONTO DOMINION BANK        DIV 2018-10-31            0            0         0      837.50         NaN           C      20181031    1250.0      671835    8755    20181031              0             1               0    20181031
894294     I8LN9QE                  APPLE INC        DIV 2018-11-15            0            0         0       65.42         NaN           C      20181115      80.0      033740   36128    20181115              0             1               0    20181115
939632     I8LN9QE       ROYAL BANK OF CANADA        DIV 2018-11-23            0            0         0      906.50         NaN           C      20181123     925.0      591131    8216    20181123              0             1               0    20181123
1577774    I8LN9QE  USD/CAD 6DH0R8F @1.352000         FX 2019-01-02            0            0         0    97632.69         NaN           C      20190102       NaN         NaN   19912    20190102              0             1               0    20190102
1577775    I8LN9QE   CDN IMPERIAL BK COMMERCE        BUY 2019-01-02            0            0         1   -85847.00  102.050000           C      20190102     840.0      118224   19913    20190102              0             1               1    20190104
1577776    I8LN9QE     CANNTRUST HOLDINGS INC        BUY 2019-01-02            0            0         1   -14720.00    6.950000           C      20190102    2100.0      14439H   19914    20190102              0             1               1    20190104
1930371    I8LN9QE      TORONTO DOMINION BANK        DIV 2019-01-31            0            0         0      837.50         NaN           C      20190131    1250.0      671835   10023    20190131              0             1               0    20190131
2118578    I8LN9QE                  APPLE INC        DIV 2019-02-14            0            0         0       65.99         NaN           C      20190214      80.0      033740   41002    20190214              0             1               0    20190214
2182633    I8LN9QE       ROYAL BANK OF CANADA        DIV 2019-02-22            0            0         0      906.50         NaN           C      20190222     925.0      591131    7758    20190222              0             1               0    20190222
2248058    I8LN9QE     CONT TO RRSP 6D-H0R8-S     TO-RSP 2019-02-28            0            0         0    -1848.00         NaN           C      20190228       NaN         NaN    8838    20190228              0             1               0    20190228
2248059    I8LN9QE     CANNTRUST HOLDINGS INC     TO-RSP 2019-02-28            1            0         0   -28152.00   12.240000           C      20190228       NaN         NaN    8839    20190228              0             1               0    20190228
2248060    I8LN9QE     CANNTRUST HOLDINGS INC     TO-RSP 2019-02-28            1            0         0    28152.00   12.240000           C      20190228   -2300.0      14439H    8840    20190228              0             1               1    20190228
2350768    I8LN9QE      TITAN MEDICAL INC-NEW       SELL 2019-03-11            0            0         1     4605.00    4.730000           C      20190311   -1000.0      66908B    6520    20190311              0             1               1    20190311
2362891    I8LN9QE      TITAN MEDICAL INC-NEW    CXLSELL 2019-03-12            0            1         1    -4605.00    4.730000           C      20190312    1000.0      66908B    9717    20190311              0             1               1    20190311
2362892    I8LN9QE      TITAN MEDICAL INC-NEW       SELL 2019-03-12            0            0         1     4605.00    4.730000           C      20190312   -1000.0      66908B    9718    20190311              0             1               1    20190311
2560136    I8LN9QE      TITAN MEDICAL INC-NEW        BUY 2019-03-20            0            0         1    -4557.36    3.400000           U      20190320    1000.0      66908B    3179    20190320              0             1               1    20190321
2566088    I8LN9QE  WTS-TITAN MEDICAL 21MAR24        BUY 2019-03-21            0            0         1         NaN         NaN           U      20190321    1000.0      91661X    5103    20190321              0             1               1    20190321
2998135    I8LN9QE   CDN IMPERIAL BK COMMERCE        DIV 2019-04-29            0            0         0     1176.00         NaN           C      20190429     840.0      118224   25137    20190429              0             1               0    20190429
3020358    I8LN9QE      TORONTO DOMINION BANK        DIV 2019-04-30            0            0         0      925.00         NaN           C      20190430    1250.0      671835   15418    20190430              0             1               0    20190430
3219312    I8LN9QE                  APPLE INC        DIV 2019-05-16            0            0         0       70.25         NaN           C      20190516      80.0      033740    6416    20190516              0             1               0    20190516
3255749    I8LN9QE       ROYAL BANK OF CANADA        DIV 2019-05-24            0            0         0      943.50         NaN           C      20190524     925.0      591131    7500    20190524              0             1               0    20190524
3528334    I8LN9QE     CANNTRUST HOLDINGS INC        BUY 2019-06-14            0            0         1   -33025.00    6.580000           C      20190614    5000.0      14439H   80428    20190614              0             1               1    20190618
4043571    I8LN9QE         INTEREST TO JUL 16        INT 2019-07-19            0            0         0     -157.55         NaN           C      20190719       NaN         NaN    5267    20190716              0             1               0    20190716
4106106    I8LN9QE   CDN IMPERIAL BK COMMERCE        DIV 2019-07-29            0            0         0     1176.00         NaN           C      20190729     840.0      118224   27274    20190729              0             1               0    20190729
4138069    I8LN9QE      TORONTO DOMINION BANK        DIV 2019-07-31            0            0         0      925.00         NaN           C      20190731    1250.0      671835    9634    20190731              0             1               0    20190731
62419      I8LN9QF                  APPLE INC        DIV 2018-08-16            0            0         0      131.55         NaN           U      20180816     212.0      033740    4975    20180816              0             1               0    20180816
475282     I8LN9QF               ALLEGION PLC        NRT 2018-09-28            0            0         0       -4.20         NaN           U      20180928     100.0      01442A   12756    20180928              0             1               0    20180928
475283     I8LN9QF               ALLEGION PLC        DIV 2018-09-28            0            0         0       21.00         NaN           U      20180928     100.0      01442A   12757    20180928              0             1               0    20180928
894295     I8LN9QF                  APPLE INC        DIV 2018-11-15            0            0         0      131.55         NaN           U      20181115     212.0      033740   36129    20181115              0             1               0    20181115
1402195    I8LN9QF          FACEBOOK INC CL-A       SELL 2018-12-19            0            0         1    70701.32  134.909052           U      20181219    -525.0      257440   17286    20181219              0             1               1    20181221
1527506    I8LN9QF               ALLEGION PLC        NRT 2018-12-28            0            0         0       -4.20         NaN           U      20181228     100.0      01442A   10616    20181228              0             1               0    20181228
1527507    I8LN9QF               ALLEGION PLC        DIV 2018-12-28            0            0         0       21.00         NaN           U      20181228     100.0      01442A   10617    20181228              0             1               0    20181228
1577777    I8LN9QF  USD/CAD 6DH0R8E @1.352000         FX 2019-01-02            0            0         0   -72213.53         NaN           U      20190102       NaN         NaN   19915    20190102              0             1               0    20190102
2118579    I8LN9QF                  APPLE INC        DIV 2019-02-14            0            0         0      131.55         NaN           U      20190214     212.0      033740   41003    20190214              0             1               0    20190214
2651415    I8LN9QF               ALLEGION PLC        NRT 2019-03-29            0            0         0       -5.40         NaN           U      20190329     100.0      01442A   16015    20190329              0             1               0    20190329
2651416    I8LN9QF               ALLEGION PLC        DIV 2019-03-29            0            0         0       27.00         NaN           U      20190329     100.0      01442A   16016    20190329              0             1               0    20190329
3219313    I8LN9QF                  APPLE INC        DIV 2019-05-16            0            0         0      138.75         NaN           U      20190516     212.0      033740    6417    20190516              0             1               0    20190516
3721521    I8LN9QF               ALLEGION PLC        NRT 2019-06-28            0            0         0       -5.40         NaN           U      20190628     100.0      01442A   19615    20190628              0             1               0    20190628
3721522    I8LN9QF               ALLEGION PLC        DIV 2019-06-28            0            0         0       27.00         NaN           U      20190628     100.0      01442A   19616    20190628              0             1               0    20190628
358757     I8LN9QS           CLIENT ADMIN FEE        A01 2018-09-17            0            0         0      -37.50         NaN           C      20180917       NaN         NaN   99284    20180915              0             1               0    20180915
358758     I8LN9QS                        HST        HS3 2018-09-17            0            0         0       -4.88         NaN           C      20180917       NaN         NaN   99285    20180915              0             1               0    20180915
516123     I8LN9QS      BIRCHCLIFF ENERGY LTD        DIV 2018-10-01            0            0         0      100.00         NaN           C      20181001    4000.0      075695   36568    20181001              0             1               0    20181001
733751     I8LN9QS   CDN IMPERIAL BK COMMERCE        DIV 2018-10-29            0            0         0      544.00         NaN           C      20181029     400.0      118224   25055    20181029              0             1               0    20181029
1306141    I8LN9QS           CLIENT ADMIN FEE        A01 2018-12-17            0            0         0      -37.50         NaN           C      20181217       NaN         NaN   75659    20181215              0             1               0    20181215
1306142    I8LN9QS                        HST        HS3 2018-12-17            0            0         0       -4.88         NaN           C      20181217       NaN         NaN   75660    20181215              0             1               0    20181215
1550570    I8LN9QS      BIRCHCLIFF ENERGY LTD        DIV 2018-12-31            0            0         0      100.00         NaN           C      20181231    4000.0      075695   20572    20181231              0             1               0    20181231
1577778    I8LN9QS   CDN IMPERIAL BK COMMERCE        BUY 2019-01-02            0            0         1   -19501.20  101.980000           C      20190102     190.0      118224   19916    20190102              0             1               1    20190104
1890339    I8LN9QS   CDN IMPERIAL BK COMMERCE        DIV 2019-01-28            0            0         0      544.00         NaN           C      20190128     400.0      118224   24522    20190128              0             1               0    20190128
2248061    I8LN9QS               CONTRIBUTION       CONT 2019-02-28            0            0         0     1848.00         NaN           C      20190228       NaN         NaN    8841    20190228              0             1               0    20190228
2248062    I8LN9QS     CANNTRUST HOLDINGS INC       CONT 2019-02-28            1            0         0    28152.00   12.240000           C      20190228       NaN         NaN    8842    20190228              0             1               0    20190228
2248063    I8LN9QS     CANNTRUST HOLDINGS INC       CONT 2019-02-28            1            0         0   -28152.00   12.240000           C      20190228    2300.0      14439H    8843    20190228              0             1               1    20190228
2500640    I8LN9QS           CLIENT ADMIN FEE        A01 2019-03-15            0            0         0      -37.50         NaN           C      20190315       NaN         NaN  109518    20190315              0             1               0    20190315
2500641    I8LN9QS                        HST        HS3 2019-03-15            0            0         0       -4.88         NaN           C      20190315       NaN         NaN  109519    20190315              0             1               0    20190315
2696391    I8LN9QS      BIRCHCLIFF ENERGY LTD        DIV 2019-04-01            0            0         0      105.00         NaN           C      20190401    4000.0      075695   40742    20190401              0             1               0    20190401
2998136    I8LN9QS   CDN IMPERIAL BK COMMERCE        DIV 2019-04-29            0            0         0      826.00         NaN           C      20190429     590.0      118224   25138    20190429              0             1               0    20190429
3309332    I8LN9QS                  HEXO CORP       EXCH 2019-05-31            0            0         0         NaN         NaN           C      20190531    1899.0      32082F    8399    20190531              0             1               1    20190531
3309333    I8LN9QS  NEWSTRIKE BRANDS LTD    *       EXCH 2019-05-31            0            0         0         NaN         NaN           C      20190531  -30000.0      46811H    8400    20190531              0             1               1    20190531
3405518    I8LN9QS                  HEXO CORP      FRACT 2019-06-07            0            0         0        5.14         NaN           C      20190607       NaN      32082F    5759    20190607              0             1               1    20190607
3528335    I8LN9QS           CLIENT ADMIN FEE        A01 2019-06-14            0            0         0      -37.50         NaN           C      20190614       NaN         NaN   80429    20190614              0             1               0    20190615
3528336    I8LN9QS                        HST        HS3 2019-06-14            0            0         0       -4.88         NaN           C      20190614       NaN         NaN   80430    20190614              0             1               0    20190615
3771008    I8LN9QS      BIRCHCLIFF ENERGY LTD        DIV 2019-07-02            0            0         0      105.00         NaN           C      20190702    4000.0      075695   43351    20190702              0             1               0    20190702
4106107    I8LN9QS   CDN IMPERIAL BK COMMERCE        DIV 2019-07-29            0            0         0      826.00         NaN           C      20190729     590.0      118224   27275    20190729              0             1               0    20190729
1402196    I8LN9QW      SILVERCORP METALS INC        DIV 2018-12-19            0            0         0       11.72         NaN           C      20181219     700.0      615691   17287    20181219              0             1               0    20181219
3721523    I8LN9QW      SILVERCORP METALS INC        DIV 2019-06-28            0            0         0       11.41         NaN           C      20190628     700.0      615691   19617    20190628              0             1               0    20190628

## sp200_position_multi_fill.csv

* 259527 rows and 8 columns
* 42963 accounts
* trading dates range from 2018-08-13 to 2019-08-12         ---> 253 trading days

       account_id  file_date  funds_of_price  pos_seq_id      price  quantity security_id  seq_id
37415     I8LN9QE 2018-10-10             NaN        4541   51.52704     -1350      070623     973
37416     I8LN9QE 2018-10-10             NaN        4542   12.10000      5900      14439H     974
87832     I8LN9QE 2019-01-02             NaN       19913  102.05000       840      118224     627
87833     I8LN9QE 2019-01-02             NaN       19914    6.95000      2100      14439H     628
142914    I8LN9QE 2019-03-11             NaN        6520    4.73000     -1000      66908B     849
143853    I8LN9QE 2019-03-12             NaN        9717    4.73000      1000      66908B     693
143854    I8LN9QE 2019-03-12             NaN        9718    4.73000     -1000      66908B     694
149947    I8LN9QE 2019-03-20             NaN        3179    3.40000      1000      66908B     825
151276    I8LN9QE 2019-03-21             NaN        5103        NaN      1000      91661X    1000
218182    I8LN9QE 2019-06-14             NaN       80428    6.58000      5000      14439H     711
81225     I8LN9QF 2018-12-19             NaN       17286  134.91500      -400      257440    1300
81226     I8LN9QF 2018-12-19             NaN       17286  134.89000      -100      257440    1301
81227     I8LN9QF 2018-12-19             NaN       17286  134.89010       -25      257440    1302
87834     I8LN9QS 2019-01-02             NaN       19916  101.98000       190      118224     629

## sp200_position_trade_grp.csv

* 254870 rows and 23 columns
* 42963 accounts
* trading dates range from 2018-08-13 to 2019-08-12         ---> 253 trading days

       account_id  bc_fee_cd  buy_sell_ind  empl_discount_ind  exchange_rate  file_date funds_of_price inventory_cd market_cd  multifill_ind orig_trade_account_id  pos_seq_id  qssp_coverage_ind rep_code security_id  seq_id special_tax_cd submit_loc_cd funds_of_price.1 trade_basis  trade_cancelled  trade_code trade_num
36705     I8LN9QE        NaN             1                  0            NaN 2018-10-10              C          NaN         T              0                   NaN        4541                  0     0RC2      070623     957            NaN             T                C           P                0           0     16515
36706     I8LN9QE        0.0             0                  0            NaN 2018-10-10              C          NaN         T              0                   NaN        4542                  0     0RC2      14439H     958            NaN             T                C           A                0           0     16594
86353     I8LN9QE        0.0             0                  0            NaN 2019-01-02              C          NaN         T              0                   NaN       19913                  0     0RC2      118224     620            NaN             T                C           A                0           0     59240
86354     I8LN9QE        0.0             0                  0            NaN 2019-01-02              C          NaN         T              0                   NaN       19914                  0     0RC2      14439H     621            NaN             T                C           A                0           0     59029
140554    I8LN9QE        0.0             1                  0            NaN 2019-03-11              C          NaN         T              0                   NaN        6520                  0     GCGJ      66908B     821            NaN             T                C           A                0           0     43778
141470    I8LN9QE        0.0             0                  0            NaN 2019-03-12              C          NaN         T              0                   NaN        9717                  0     GCGJ      66908B     672            NaN             T                C           A                1           0     43778
141471    I8LN9QE        0.0             1                  0            NaN 2019-03-12              C          NaN         T              0                   NaN        9718                  0     0RC2      66908B     673            NaN             T                C           A                0           0     62331
147461    I8LN9QE        NaN             0                  0          34.04 2019-03-20              U          NaN        NU              0               I8LN9QE        3179                  0     0RC2      66908B     814            NaN             T                U           P                0           0     03379
148770    I8LN9QE        NaN             0                  0          34.71 2019-03-21              U          NaN        NU              0                   NaN        5103                  0     0RC2      91661X     981            NaN             T                U           P                0           0      3225
214422    I8LN9QE        0.0             0                  0            NaN 2019-06-14              C          NaN         T              0                   NaN       80428                  0     0RC2      14439H     701            NaN             T                C           A                0           0     97750
79857     I8LN9QF        0.0             1                  0            NaN 2018-12-19              U          NaN        UU              0                   NaN       17286                  0     0RC2      257440    1293            NaN             T                U           A                0           0     24010
86355     I8LN9QS        NaN             0                  0            NaN 2019-01-02              C          NaN         T              0                   NaN       19916                  0     0RC2      118224     622            NaN             T                C           P                0           0     59093

# SP399 (RRWS DAILY RECONCILIATION FILE)

1.   cust_sp399_evaluation.csv
2.   cust_sp399_positions.csv (file is too large to load with other datasets, will provide later)
3.   sp399_balance_grp.csv
4.   sp399_evaluation_grp.csv

## cust_sp399_evaluation.csv

* 8891238 rows and 16 columns
* 97014 accounts
* 354 advisors
* trading dates range from 2019-03-29 to 2019-08-12         ---> 95 trading days

        acct_service_code acct_rep account_id  acct_summ_td_net_amt  acct_summ_sd_net_amt  acct_summ_mkt_value  acct_summ_loan_value  acct_summ_sfk_loan_value  acct_summ_rtm_value  acct_summ_rts_value  acct_summ_rtm_value_alt  acct_summ_loan_value_alt  acct_summ_rts_value_alt  acct_summ_sfk_loan_val_alt  acct_summ_mkt_value_alt  file_date
56262        000000000000     0RC2    I8LN9QE               -359.90               -359.90            357799.49             236556.44                       0.0           -236916.34                  0.0               -236916.34                 236556.44                      0.0                         0.0                357799.49 2019-03-29
145671       000000000000     0RC2    I8LN9QE               -359.90               -359.90            363979.15             240603.60                       0.0           -240963.50                  0.0               -240963.50                 240603.60                      0.0                         0.0                363979.15 2019-04-01
235331       000000000000     0RC2    I8LN9QE               -359.90               -359.90            362408.44             240373.51                       0.0           -240733.41                  0.0               -240733.41                 240373.51                      0.0                         0.0                362408.44 2019-04-03
325128       000000000000     0RC2    I8LN9QE               -359.90               -359.90            363112.37             240972.46                       0.0           -241332.36                  0.0               -241332.36                 240972.46                      0.0                         0.0                363112.37 2019-04-04
415007       000000000000     0RC2    I8LN9QE               -359.90               -359.90            365634.10             242303.87                       0.0           -242663.77                  0.0               -242663.77                 242303.87                      0.0                         0.0                365634.10 2019-04-05
504958       000000000000     0RC2    I8LN9QE               -359.90               -359.90            365742.65             242416.66                       0.0           -242776.56                  0.0               -242776.56                 242416.66                      0.0                         0.0                365742.65 2019-04-08
595018       000000000000     0RC2    I8LN9QE               -359.90               -359.90            361285.29             238214.70                       0.0           -238574.60                  0.0               -238574.60                 238214.70                      0.0                         0.0                361285.29 2019-04-09
685157       000000000000     0RC2    I8LN9QE               -359.90               -359.90            362834.23             240664.16                       0.0           -241024.06                  0.0               -241024.06                 240664.16                      0.0                         0.0                362834.23 2019-04-10
775360       000000000000     0RC2    I8LN9QE               -359.90               -359.90            360291.44             239458.41                       0.0           -239818.31                  0.0               -239818.31                 239458.41                      0.0                         0.0                360291.44 2019-04-11
865666       000000000000     0RC2    I8LN9QE               -359.90               -359.90            362950.23             241253.56                       0.0           -241613.46                  0.0               -241613.46                 241253.56                      0.0                         0.0                362950.23 2019-04-12
956105       000000000000     0RC2    I8LN9QE               -359.90               -359.90            361875.76             240967.63                       0.0           -241327.53                  0.0               -241327.53                 240967.63                      0.0                         0.0                361875.76 2019-04-15
1046628      000000000000     0RC2    I8LN9QE               -359.90               -359.90            363235.82             241994.68                       0.0           -242354.58                  0.0               -242354.58                 241994.68                      0.0                         0.0                363235.82 2019-04-16
1137221      000000000000     0RC2    I8LN9QE               -359.90               -359.90            367855.09             244579.16                       0.0           -244939.06                  0.0               -244939.06                 244579.16                      0.0                         0.0                367855.09 2019-04-17
1227936      000000000000     0RC2    I8LN9QE               -359.90               -359.90            367310.97             244487.28                       0.0           -244847.18                  0.0               -244847.18                 244487.28                      0.0                         0.0                367310.97 2019-04-18
1318780      000000000000     0RC2    I8LN9QE               -359.90               -359.90            367289.84             244347.89                       0.0           -244707.79                  0.0               -244707.79                 244347.89                      0.0                         0.0                367289.84 2019-04-22
1409719      000000000000     0RC2    I8LN9QE               -359.90               -359.90            370668.82             246270.98                       0.0           -246630.88                  0.0               -246630.88                 246270.98                      0.0                         0.0                370668.82 2019-04-23
1500751      000000000000     0RC2    I8LN9QE               -359.90               -359.90            370600.35             245466.85                       0.0           -245826.75                  0.0               -245826.75                 245466.85                      0.0                         0.0                370600.35 2019-04-24
1591847      000000000000     0RC2    I8LN9QE               -359.90               -359.90            370173.45             245469.01                       0.0           -245828.91                  0.0               -245828.91                 245469.01                      0.0                         0.0                370173.45 2019-04-25
1683004      000000000000     0RC2    I8LN9QE               -359.90               -359.90            369939.47             245554.63                       0.0           -245914.53                  0.0               -245914.53                 245554.63                      0.0                         0.0                369939.47 2019-04-26
1774240      000000000000     0RC2    I8LN9QE              -1535.90              -1535.90            371088.01             246598.81                       0.0           -248134.71                  0.0               -248134.71                 246598.81                      0.0                         0.0                371088.01 2019-04-29
1865550      000000000000     0RC2    I8LN9QE              -2460.90              -2460.90            368409.51             245248.06                       0.0           -247708.96                  0.0               -247708.96                 245248.06                      0.0                         0.0                368409.51 2019-04-30
1956953      000000000000     0RC2    I8LN9QE              -2460.90              -2460.90            366572.07             244485.05                       0.0           -246945.95                  0.0               -246945.95                 244485.05                      0.0                         0.0                366572.07 2019-05-01
2048437      000000000000     0RC2    I8LN9QE              -2460.90              -2460.90            359823.54             241078.09                       0.0           -243538.99                  0.0               -243538.99                 241078.09                      0.0                         0.0                359823.54 2019-05-02
2139984      000000000000     0RC2    I8LN9QE              -2460.90              -2460.90            364244.12             243612.08                       0.0           -246072.98                  0.0               -246072.98                 243612.08                      0.0                         0.0                364244.12 2019-05-03
2231626      000000000000     0RC2    I8LN9QE              -2460.90              -2460.90            362837.42             242819.40                       0.0           -245280.30                  0.0               -245280.30                 242819.40                      0.0                         0.0                362837.42 2019-05-06
2323354      000000000000     0RC2    I8LN9QE              -2460.90              -2460.90            358469.40             240046.38                       0.0           -242507.28                  0.0               -242507.28                 240046.38                      0.0                         0.0                358469.40 2019-05-07
2415161      000000000000     0RC2    I8LN9QE              -2460.90              -2460.90            357963.87             239612.31                       0.0           -242073.21                  0.0               -242073.21                 239612.31                      0.0                         0.0                357963.87 2019-05-08
2507017      000000000000     0RC2    I8LN9QE              -2460.90              -2460.90            354723.60             237748.92                       0.0           -240209.82                  0.0               -240209.82                 237748.92                      0.0                         0.0                354723.60 2019-05-09
2599009      000000000000     0RC2    I8LN9QE              -2460.90              -2460.90            354558.98             237307.89                       0.0           -239768.79                  0.0               -239768.79                 237307.89                      0.0                         0.0                354558.98 2019-05-10
2691077      000000000000     0RC2    I8LN9QE              -2460.90              -2460.90            349436.12             233852.89                       0.0           -236313.79                  0.0               -236313.79                 233852.89                      0.0                         0.0                349436.12 2019-05-13
2783235      000000000000     0RC2    I8LN9QE              -2460.90              -2460.90            353950.92             236441.05                       0.0           -238901.95                  0.0               -238901.95                 236441.05                      0.0                         0.0                353950.92 2019-05-14
2875553      000000000000     0RC2    I8LN9QE              -2460.90              -2460.90            355238.63             237161.85                       0.0           -239622.75                  0.0               -239622.75                 237161.85                      0.0                         0.0                355238.63 2019-05-15
2967993      000000000000     0RC2    I8LN9QE              -2531.15              -2531.15            355530.74             237588.73                       0.0           -240119.88                  0.0               -240119.88                 237588.73                      0.0                         0.0                355530.74 2019-05-16
3060505      000000000000     0RC2    I8LN9QE              -2531.15              -2531.15            354453.26             237045.68                       0.0           -239576.83                  0.0               -239576.83                 237045.68                      0.0                         0.0                354453.26 2019-05-17
3153022      000000000000     0RC2    I8LN9QE              -2531.15              -2531.15            354876.25             235539.83                       0.0           -238070.98                  0.0               -238070.98                 235539.83                      0.0                         0.0                354876.25 2019-05-20
3245633      000000000000     0RC2    I8LN9QE              -2531.15              -2531.15            354331.02             237183.92                       0.0           -239715.07                  0.0               -239715.07                 237183.92                      0.0                         0.0                354331.02 2019-05-21
3338348      000000000000     0RC2    I8LN9QE              -2531.15              -2531.15            349885.43             233953.40                       0.0           -236484.55                  0.0               -236484.55                 233953.40                      0.0                         0.0                349885.43 2019-05-22
3431120      000000000000     0RC2    I8LN9QE              -2531.15              -2531.15            344519.31             230586.52                       0.0           -233117.67                  0.0               -233117.67                 230586.52                      0.0                         0.0                344519.31 2019-05-23
3523950      000000000000     0RC2    I8LN9QE              -3474.65              -3474.65            347513.65             232579.16                       0.0           -236053.81                  0.0               -236053.81                 232579.16                      0.0                         0.0                347513.65 2019-05-24
3616991      000000000000     0RC2    I8LN9QE              -3474.65              -3474.65            349664.53             233913.17                       0.0           -237387.82                  0.0               -237387.82                 233913.17                      0.0                         0.0                349664.53 2019-05-27
3710110      000000000000     0RC2    I8LN9QE              -3474.65              -3474.65            348200.83             232726.18                       0.0           -236200.83                  0.0               -236200.83                 232726.18                      0.0                         0.0                348200.83 2019-05-28
3803299      000000000000     0RC2    I8LN9QE              -3474.65              -3474.65            343345.47             229772.63                       0.0           -233247.28                  0.0               -233247.28                 229772.63                      0.0                         0.0                343345.47 2019-05-29
3896557      000000000000     0RC2    I8LN9QE              -3474.65              -3474.65            340839.79             228316.25                       0.0           -231790.90                  0.0               -231790.90                 228316.25                      0.0                         0.0                340839.79 2019-05-30
3989892      000000000000     0RC2    I8LN9QE              -3474.65              -3474.65            337123.75             226022.43                       0.0           -229497.08                  0.0               -229497.08                 226022.43                      0.0                         0.0                337123.75 2019-05-31
4083360      000000000000     0RC2    I8LN9QE              -3474.65              -3474.65            335914.38             225453.87                       0.0           -228928.52                  0.0               -228928.52                 225453.87                      0.0                         0.0                335914.38 2019-06-03
4176891      000000000000     0RC2    I8LN9QE              -3474.65              -3474.65            341258.29             237204.00                       0.0           -240678.65                  0.0               -240678.65                 237204.00                      0.0                         0.0                341258.29 2019-06-04
4270649      000000000000     0RC2    I8LN9QE              -3474.65              -3474.65            341077.17             237012.42                       0.0           -240487.07                  0.0               -240487.07                 237012.42                      0.0                         0.0                341077.17 2019-06-05
4364499      000000000000     0RC2    I8LN9QE              -3474.65              -3474.65            340651.91             236779.54                       0.0           -240254.19                  0.0               -240254.19                 236779.54                      0.0                         0.0                340651.91 2019-06-06
4458416      000000000000     0RC2    I8LN9QE              -3474.65              -3474.65            340813.30             236935.31                       0.0           -240409.96                  0.0               -240409.96                 236935.31                      0.0                         0.0                340813.30 2019-06-07
4552415      000000000000     0RC2    I8LN9QE              -3474.65              -3474.65            342525.80             238100.06                       0.0           -241574.71                  0.0               -241574.71                 238100.06                      0.0                         0.0                342525.80 2019-06-10
4646542      000000000000     0RC2    I8LN9QE              -3474.65              -3474.65            342138.94             236314.36                       0.0           -239789.01                  0.0               -239789.01                 236314.36                      0.0                         0.0                342138.94 2019-06-11
4740826      000000000000     0RC2    I8LN9QE              -3474.65              -3474.65            339321.39             234475.08                       0.0           -237949.73                  0.0               -237949.73                 234475.08                      0.0                         0.0                339321.39 2019-06-12
4835145      000000000000     0RC2    I8LN9QE              -3474.65              -3474.65            338430.18             233851.23                       0.0           -237325.88                  0.0               -237325.88                 233851.23                      0.0                         0.0                338430.18 2019-06-13
4929541      000000000000     0RC2    I8LN9QE              29550.35              -3474.65            373895.25             258684.48                       0.0           -229134.13                  0.0               -238779.13                 235304.48                      0.0                         0.0                340495.25 2019-06-14
5023999      000000000000     0RC2    I8LN9QE              29550.35              -3474.65            374512.27             260705.79                       0.0           -231155.44                  0.0               -240765.44                 237290.79                      0.0                         0.0                341062.27 2019-06-17
5118495      000000000000     0RC2    I8LN9QE              29550.35              29550.35            377971.81             263215.27                       0.0           -233664.92                  0.0               -233664.92                 263215.27                      0.0                         0.0                377971.81 2019-06-18
5213064      000000000000     0RC2    I8LN9QE              29550.35              29550.35            382764.01             266455.61                       0.0           -236905.26                  0.0               -236905.26                 266455.61                      0.0                         0.0                382764.01 2019-06-19

## sp399_balance_grp.csv

* 81295990 rows and 9 columns
* 97208 accounts
* trading dates range from 2018-08-13 to 2019-08-12         ---> 254 trading days

         account_id   amount  file_date  quantity security_id  seq_id  txn_bv_mv_ind  valid_amount  valid_quantity
206070      I8LN9QE  1599.78 2018-08-13       NaN         NaN  206531              0             1               0
206071      I8LN9QE      NaN 2018-08-13      80.0      033740  206532              0             0               1
206072      I8LN9QE      NaN 2018-08-13    1350.0      070623  206533              0             0               1
206073      I8LN9QE      NaN 2018-08-13   16000.0      28843F  206534              0             0               1
206074      I8LN9QE      NaN 2018-08-13     925.0      591131  206535              0             0               1
206075      I8LN9QE      NaN 2018-08-13    1100.0      66908B  206536              0             0               1
206076      I8LN9QE      NaN 2018-08-13    1250.0      671835  206537              0             0               1
206077      I8LN9QE      NaN 2018-08-13   20000.0      91661P  206538              0             0               1
206078      I8LN9QE      NaN 2018-08-13   30000.0      91661S  206539              0             0               1
206079      I8LN9QE      NaN 2018-08-13   33000.0      91661T  206540              0             0               1
486224      I8LN9QE  1599.78 2018-08-14       NaN         NaN  206726              0             1               0
486225      I8LN9QE      NaN 2018-08-14      80.0      033740  206727              0             0               1
486226      I8LN9QE      NaN 2018-08-14    1350.0      070623  206728              0             0               1
486227      I8LN9QE      NaN 2018-08-14   16000.0      28843F  206729              0             0               1
486228      I8LN9QE      NaN 2018-08-14     925.0      591131  206730              0             0               1
486229      I8LN9QE      NaN 2018-08-14    1100.0      66908B  206731              0             0               1
486230      I8LN9QE      NaN 2018-08-14    1250.0      671835  206732              0             0               1
486231      I8LN9QE      NaN 2018-08-14   20000.0      91661P  206733              0             0               1
486232      I8LN9QE      NaN 2018-08-14   30000.0      91661S  206734              0             0               1
486233      I8LN9QE      NaN 2018-08-14   33000.0      91661T  206735              0             0               1
766555      I8LN9QE  1599.78 2018-08-15       NaN         NaN  206944              0             1               0
766556      I8LN9QE      NaN 2018-08-15      80.0      033740  206945              0             0               1
766557      I8LN9QE      NaN 2018-08-15    1350.0      070623  206946              0             0               1
766558      I8LN9QE      NaN 2018-08-15   16000.0      28843F  206947              0             0               1
766559      I8LN9QE      NaN 2018-08-15     925.0      591131  206948              0             0               1
766560      I8LN9QE      NaN 2018-08-15    1100.0      66908B  206949              0             0               1
766561      I8LN9QE      NaN 2018-08-15    1250.0      671835  206950              0             0               1
766562      I8LN9QE      NaN 2018-08-15   20000.0      91661P  206951              0             0               1
766563      I8LN9QE      NaN 2018-08-15   30000.0      91661S  206952              0             0               1
766564      I8LN9QE      NaN 2018-08-15   33000.0      91661T  206953              0             0               1
1047061     I8LN9QE  1664.91 2018-08-16       NaN         NaN  207136              0             1               0
1047062     I8LN9QE      NaN 2018-08-16      80.0      033740  207137              0             0               1
1047063     I8LN9QE      NaN 2018-08-16    1350.0      070623  207138              0             0               1
1047064     I8LN9QE      NaN 2018-08-16   16000.0      28843F  207139              0             0               1
1047065     I8LN9QE      NaN 2018-08-16     925.0      591131  207140              0             0               1
1047066     I8LN9QE      NaN 2018-08-16    1100.0      66908B  207141              0             0               1
1047067     I8LN9QE      NaN 2018-08-16    1250.0      671835  207142              0             0               1
1047068     I8LN9QE      NaN 2018-08-16   20000.0      91661P  207143              0             0               1
1047069     I8LN9QE      NaN 2018-08-16   30000.0      91661S  207144              0             0               1
1047070     I8LN9QE      NaN 2018-08-16   33000.0      91661T  207145              0             0               1
1327659     I8LN9QE  1664.91 2018-08-17       NaN         NaN  207235              0             1               0
1327660     I8LN9QE      NaN 2018-08-17      80.0      033740  207236              0             0               1
1327661     I8LN9QE      NaN 2018-08-17    1350.0      070623  207237              0             0               1
1327662     I8LN9QE      NaN 2018-08-17   16000.0      28843F  207238              0             0               1
1327663     I8LN9QE      NaN 2018-08-17     925.0      591131  207239              0             0               1
1327664     I8LN9QE      NaN 2018-08-17    1100.0      66908B  207240              0             0               1
1327665     I8LN9QE      NaN 2018-08-17    1250.0      671835  207241              0             0               1
1327666     I8LN9QE      NaN 2018-08-17   20000.0      91661P  207242              0             0               1
1327667     I8LN9QE      NaN 2018-08-17   30000.0      91661S  207243              0             0               1
1327668     I8LN9QE      NaN 2018-08-17   33000.0      91661T  207244              0             0               1
1608328     I8LN9QE  1664.91 2018-08-20       NaN         NaN  207410              0             1               0
1608329     I8LN9QE      NaN 2018-08-20      80.0      033740  207411              0             0               1
1608330     I8LN9QE      NaN 2018-08-20    1350.0      070623  207412              0             0               1
1608331     I8LN9QE      NaN 2018-08-20   16000.0      28843F  207413              0             0               1
1608332     I8LN9QE      NaN 2018-08-20     925.0      591131  207414              0             0               1
1608333     I8LN9QE      NaN 2018-08-20    1100.0      66908B  207415              0             0               1
1608334     I8LN9QE      NaN 2018-08-20    1250.0      671835  207416              0             0               1
1608335     I8LN9QE      NaN 2018-08-20   20000.0      91661P  207417              0             0               1
1608336     I8LN9QE      NaN 2018-08-20   30000.0      91661S  207418              0             0               1
1608337     I8LN9QE      NaN 2018-08-20   33000.0      91661T  207419              0             0               1
1889330     I8LN9QE  1664.91 2018-08-21       NaN         NaN  207739              0             1               0
1889331     I8LN9QE      NaN 2018-08-21      80.0      033740  207740              0             0               1
1889332     I8LN9QE      NaN 2018-08-21    1350.0      070623  207741              0             0               1
1889333     I8LN9QE      NaN 2018-08-21   16000.0      28843F  207742              0             0               1
1889334     I8LN9QE      NaN 2018-08-21     925.0      591131  207743              0             0               1
1889335     I8LN9QE      NaN 2018-08-21    1100.0      66908B  207744              0             0               1
1889336     I8LN9QE      NaN 2018-08-21    1250.0      671835  207745              0             0               1
1889337     I8LN9QE      NaN 2018-08-21   20000.0      91661P  207746              0             0               1
1889338     I8LN9QE      NaN 2018-08-21   30000.0      91661S  207747              0             0               1
1889339     I8LN9QE      NaN 2018-08-21   33000.0      91661T  207748              0             0               1
2170594     I8LN9QE  1664.91 2018-08-22       NaN         NaN  207974              0             1               0
2170595     I8LN9QE      NaN 2018-08-22      80.0      033740  207975              0             0               1
2170596     I8LN9QE      NaN 2018-08-22    1350.0      070623  207976              0             0               1
2170597     I8LN9QE      NaN 2018-08-22   16000.0      28843F  207977              0             0               1
2170598     I8LN9QE      NaN 2018-08-22     925.0      591131  207978              0             0               1
2170599     I8LN9QE      NaN 2018-08-22    1100.0      66908B  207979              0             0               1
2170600     I8LN9QE      NaN 2018-08-22    1250.0      671835  207980              0             0               1
2170601     I8LN9QE      NaN 2018-08-22   20000.0      91661P  207981              0             0               1
2170602     I8LN9QE      NaN 2018-08-22   30000.0      91661S  207982              0             0               1
2170603     I8LN9QE      NaN 2018-08-22   33000.0      91661T  207983              0             0               1
2451951     I8LN9QE  1664.91 2018-08-23       NaN         NaN  208066              0             1               0
2451952     I8LN9QE      NaN 2018-08-23      80.0      033740  208067              0             0               1
2451953     I8LN9QE      NaN 2018-08-23    1350.0      070623  208068              0             0               1
2451954     I8LN9QE      NaN 2018-08-23   16000.0      28843F  208069              0             0               1
2451955     I8LN9QE      NaN 2018-08-23     925.0      591131  208070              0             0               1
2451956     I8LN9QE      NaN 2018-08-23    1100.0      66908B  208071              0             0               1
2451957     I8LN9QE      NaN 2018-08-23    1250.0      671835  208072              0             0               1
2451958     I8LN9QE      NaN 2018-08-23   20000.0      91661P  208073              0             0               1
2451959     I8LN9QE      NaN 2018-08-23   30000.0      91661S  208074              0             0               1
2451960     I8LN9QE      NaN 2018-08-23   33000.0      91661T  208075              0             0               1
2733434     I8LN9QE  2534.41 2018-08-24       NaN         NaN  208186              0             1               0
2733435     I8LN9QE      NaN 2018-08-24      80.0      033740  208187              0             0               1
2733436     I8LN9QE      NaN 2018-08-24    1350.0      070623  208188              0             0               1
2733437     I8LN9QE      NaN 2018-08-24   16000.0      28843F  208189              0             0               1
2733438     I8LN9QE      NaN 2018-08-24     925.0      591131  208190              0             0               1
2733439     I8LN9QE      NaN 2018-08-24    1100.0      66908B  208191              0             0               1
2733440     I8LN9QE      NaN 2018-08-24    1250.0      671835  208192              0             0               1
2733441     I8LN9QE      NaN 2018-08-24   20000.0      91661P  208193              0             0               1
2733442     I8LN9QE      NaN 2018-08-24   30000.0      91661S  208194              0             0               1
2733443     I8LN9QE      NaN 2018-08-24   33000.0      91661T  208195              0             0               1
3015200     I8LN9QE  2534.41 2018-08-27       NaN         NaN  208459              0             1               0
3015201     I8LN9QE      NaN 2018-08-27      80.0      033740  208460              0             0               1
3015202     I8LN9QE      NaN 2018-08-27    1350.0      070623  208461              0             0               1
3015203     I8LN9QE      NaN 2018-08-27   16000.0      28843F  208462              0             0               1
3015204     I8LN9QE      NaN 2018-08-27     925.0      591131  208463              0             0               1
3015205     I8LN9QE      NaN 2018-08-27    1100.0      66908B  208464              0             0               1
3015206     I8LN9QE      NaN 2018-08-27    1250.0      671835  208465              0             0               1
3015207     I8LN9QE      NaN 2018-08-27   20000.0      91661P  208466              0             0               1
3015208     I8LN9QE      NaN 2018-08-27   30000.0      91661S  208467              0             0               1
3015209     I8LN9QE      NaN 2018-08-27   33000.0      91661T  208468              0             0               1
3297333     I8LN9QE  2534.41 2018-08-28       NaN         NaN  208758              0             1               0
3297334     I8LN9QE      NaN 2018-08-28      80.0      033740  208759              0             0               1
3297335     I8LN9QE      NaN 2018-08-28    1350.0      070623  208760              0             0               1
3297336     I8LN9QE      NaN 2018-08-28   16000.0      28843F  208761              0             0               1
3297337     I8LN9QE      NaN 2018-08-28     925.0      591131  208762              0             0               1
3297338     I8LN9QE      NaN 2018-08-28    1100.0      66908B  208763              0             0               1
3297339     I8LN9QE      NaN 2018-08-28    1250.0      671835  208764              0             0               1
3297340     I8LN9QE      NaN 2018-08-28   20000.0      91661P  208765              0             0               1
3297341     I8LN9QE      NaN 2018-08-28   30000.0      91661S  208766              0             0               1
3297342     I8LN9QE      NaN 2018-08-28   33000.0      91661T  208767              0             0               1
3579598     I8LN9QE  2534.41 2018-08-29       NaN         NaN  208928              0             1               0
3579599     I8LN9QE      NaN 2018-08-29      80.0      033740  208929              0             0               1
3579600     I8LN9QE      NaN 2018-08-29    1350.0      070623  208930              0             0               1
3579601     I8LN9QE      NaN 2018-08-29   16000.0      28843F  208931              0             0               1
3579602     I8LN9QE      NaN 2018-08-29     925.0      591131  208932              0             0               1
3579603     I8LN9QE      NaN 2018-08-29    1100.0      66908B  208933              0             0               1
3579604     I8LN9QE      NaN 2018-08-29    1250.0      671835  208934              0             0               1
3579605     I8LN9QE      NaN 2018-08-29   20000.0      91661P  208935              0             0               1
3579606     I8LN9QE      NaN 2018-08-29   30000.0      91661S  208936              0             0               1
3579607     I8LN9QE      NaN 2018-08-29   33000.0      91661T  208937              0             0               1
3861944     I8LN9QE  2534.41 2018-08-30       NaN         NaN  208987              0             1               0
3861945     I8LN9QE      NaN 2018-08-30      80.0      033740  208988              0             0               1
3861946     I8LN9QE      NaN 2018-08-30    1350.0      070623  208989              0             0               1
3861947     I8LN9QE      NaN 2018-08-30   16000.0      28843F  208990              0             0               1
3861948     I8LN9QE      NaN 2018-08-30     925.0      591131  208991              0             0               1
3861949     I8LN9QE      NaN 2018-08-30    1100.0      66908B  208992              0             0               1
3861950     I8LN9QE      NaN 2018-08-30    1250.0      671835  208993              0             0               1
3861951     I8LN9QE      NaN 2018-08-30   20000.0      91661P  208994              0             0               1
3861952     I8LN9QE      NaN 2018-08-30   30000.0      91661S  208995              0             0               1
3861953     I8LN9QE      NaN 2018-08-30   33000.0      91661T  208996              0             0               1
4144601     I8LN9QE  2534.41 2018-08-31       NaN         NaN  209335              0             1               0
4144602     I8LN9QE      NaN 2018-08-31      80.0      033740  209336              0             0               1
4144603     I8LN9QE      NaN 2018-08-31    1350.0      070623  209337              0             0               1
4144604     I8LN9QE      NaN 2018-08-31   16000.0      28843F  209338              0             0               1
4144605     I8LN9QE      NaN 2018-08-31     925.0      591131  209339              0             0               1
4144606     I8LN9QE      NaN 2018-08-31    1100.0      66908B  209340              0             0               1
4144607     I8LN9QE      NaN 2018-08-31    1250.0      671835  209341              0             0               1
4144608     I8LN9QE      NaN 2018-08-31   20000.0      91661P  209342              0             0               1
4144609     I8LN9QE      NaN 2018-08-31   30000.0      91661S  209343              0             0               1
4144610     I8LN9QE      NaN 2018-08-31   33000.0      91661T  209344              0             0               1
4427500     I8LN9QE  2534.41 2018-09-04       NaN         NaN  209602              0             1               0
4427501     I8LN9QE      NaN 2018-09-04      80.0      033740  209603              0             0               1
4427502     I8LN9QE      NaN 2018-09-04    1350.0      070623  209604              0             0               1
4427503     I8LN9QE      NaN 2018-09-04   16000.0      28843F  209605              0             0               1
4427504     I8LN9QE      NaN 2018-09-04     925.0      591131  209606              0             0               1
4427505     I8LN9QE      NaN 2018-09-04    1100.0      66908B  209607              0             0               1
4427506     I8LN9QE      NaN 2018-09-04    1250.0      671835  209608              0             0               1
4427507     I8LN9QE      NaN 2018-09-04   20000.0      91661P  209609              0             0               1
4427508     I8LN9QE      NaN 2018-09-04   30000.0      91661S  209610              0             0               1
4427509     I8LN9QE      NaN 2018-09-04   33000.0      91661T  209611              0             0               1
4710596     I8LN9QE  2534.41 2018-09-05       NaN         NaN  209758              0             1               0
4710597     I8LN9QE      NaN 2018-09-05      80.0      033740  209759              0             0               1
4710598     I8LN9QE      NaN 2018-09-05    1350.0      070623  209760              0             0               1
4710599     I8LN9QE      NaN 2018-09-05   16000.0      28843F  209761              0             0               1
4710600     I8LN9QE      NaN 2018-09-05     925.0      591131  209762              0             0               1
4710601     I8LN9QE      NaN 2018-09-05    1100.0      66908B  209763              0             0               1
4710602     I8LN9QE      NaN 2018-09-05    1250.0      671835  209764              0             0               1
4710603     I8LN9QE      NaN 2018-09-05   20000.0      91661P  209765              0             0               1
4710604     I8LN9QE      NaN 2018-09-05   30000.0      91661S  209766              0             0               1
4710605     I8LN9QE      NaN 2018-09-05   33000.0      91661T  209767              0             0               1
4993722     I8LN9QE  2534.41 2018-09-06       NaN         NaN  209895              0             1               0
4993723     I8LN9QE      NaN 2018-09-06      80.0      033740  209896              0             0               1

## sp399_evaluation_grp.csv

* 13505397 rows and 13 columns
* 67933 accounts
* trading dates range from 2018-08-13 to 2019-08-12         ---> 254 trading days

         account_id  bal_seq_id  curr_vd_bal  file_date  seq_id  td_loan_val  td_mkt_val  td_req_mgn  td_req_sec  vd_loan_val  vd_mkt_val  vd_req_mgn  vd_req_sec
33464       I8LN9QE      206531      1599.78 2018-08-13   33434    199137.30   290652.86  -200737.08         NaN    199137.30   290652.86  -200737.08         NaN
79352       I8LN9QE      206726      1599.78 2018-08-14   33479    200541.89   292483.41  -202141.67         NaN    200541.89   292483.41  -202141.67         NaN
125325      I8LN9QE      206944      1599.78 2018-08-15   33553    199764.43   291515.76  -201364.21         NaN    199764.43   291515.76  -201364.21         NaN
171327      I8LN9QE      207136      1664.91 2018-08-16   33598    201295.43   293886.89  -202960.34         NaN    201295.43   293886.89  -202960.34         NaN
217408      I8LN9QE      207235      1664.91 2018-08-17   33653    202606.86   295716.38  -204271.77         NaN    202606.86   295716.38  -204271.77         NaN
263540      I8LN9QE      207410      1664.91 2018-08-20   33701    202518.31   295722.87  -204183.22         NaN    202518.31   295722.87  -204183.22         NaN
309780      I8LN9QE      207739      1664.91 2018-08-21   33767    202000.63   295391.32  -203665.54         NaN    202000.63   295391.32  -203665.54         NaN
356005      I8LN9QE      207974      1664.91 2018-08-22   33806    202696.37   296702.25  -204361.28         NaN    202696.37   296702.25  -204361.28         NaN
402287      I8LN9QE      208066      1664.91 2018-08-23   33841    202340.29   296557.55  -204005.20         NaN    202340.29   296557.55  -204005.20         NaN
448610      I8LN9QE      208186      2534.41 2018-08-24   33882    202062.16   295948.23  -204596.57         NaN    202062.16   295948.23  -204596.57         NaN
494982      I8LN9QE      208459      2534.41 2018-08-27   33913    202689.86   296593.94  -205224.27         NaN    202689.86   296593.94  -205224.27         NaN
541428      I8LN9QE      208758      2534.41 2018-08-28   33961    202635.26   296672.94  -205169.67         NaN    202635.26   296672.94  -205169.67         NaN
587869      I8LN9QE      208928      2534.41 2018-08-29   33992    203679.34   298266.48  -206213.75         NaN    203679.34   298266.48  -206213.75         NaN
634381      I8LN9QE      208987      2534.41 2018-08-30   34044    203893.74   298423.76  -206428.15         NaN    203893.74   298423.76  -206428.15         NaN
680926      I8LN9QE      209335      2534.41 2018-08-31   34077    204277.47   296946.38  -206811.88         NaN    204277.47   296946.38  -206811.88         NaN
727410      I8LN9QE      209602      2534.41 2018-09-04   34015    202588.08   296632.53  -205122.49         NaN    202588.08   296632.53  -205122.49         NaN
773794      I8LN9QE      209758      2534.41 2018-09-05   33962    203541.74   298154.91  -206076.15         NaN    203541.74   298154.91  -206076.15         NaN
820216      I8LN9QE      209895      2534.41 2018-09-06   34015    203709.23   298460.19  -206243.64         NaN    203709.23   298460.19  -206243.64         NaN
866641      I8LN9QE      210154      2534.41 2018-09-07   34105    202974.28   297330.24  -205508.69         NaN    202974.28   297330.24  -205508.69         NaN
913112      I8LN9QE      210396      2534.41 2018-09-10   34145    202508.52   296582.88  -205042.93         NaN    202508.52   296582.88  -205042.93         NaN
959664      I8LN9QE      210750      2534.41 2018-09-11   34215    203134.62   297480.31  -205669.03         NaN    203134.62   297480.31  -205669.03         NaN
1006280     I8LN9QE      211053      2534.41 2018-09-12   34278    201548.25   295071.07  -204082.66         NaN    201548.25   295071.07  -204082.66         NaN
1053001     I8LN9QE      211275      2534.41 2018-09-13   34326    201172.34   294360.05  -203706.75         NaN    201172.34   294360.05  -203706.75         NaN
1099715     I8LN9QE      211537      2534.41 2018-09-14   34373    201247.23   294288.04  -203781.64         NaN    201247.23   294288.04  -203781.64         NaN
1146826     I8LN9QE      211746      2534.41 2018-09-17   34767    201683.88   295172.83  -204218.29         NaN    201683.88   295172.83  -204218.29         NaN
1194138     I8LN9QE      211995      2534.41 2018-09-18   34790    202544.45   296399.21  -205078.86         NaN    202544.45   296399.21  -205078.86         NaN
1241500     I8LN9QE      212373      2534.41 2018-09-19   34859    201516.61   294825.87  -204051.02         NaN    201516.61   294825.87  -204051.02         NaN
1288942     I8LN9QE      212679      2534.41 2018-09-20   34908    202764.08   296637.98  -205298.49         NaN    202764.08   296637.98  -205298.49         NaN
1336497     I8LN9QE      212931      2534.41 2018-09-21   34953    202243.52   295847.31  -204777.93         NaN    202243.52   295847.31  -204777.93         NaN
1384027     I8LN9QE      213250      2534.41 2018-09-24   35025    201870.65   296106.64  -204405.06         NaN    201870.65   296106.64  -204405.06         NaN
1431622     I8LN9QE      213490      2534.41 2018-09-25   35089    201901.83   295914.18  -204436.24         NaN    201901.83   295914.18  -204436.24         NaN
1479312     I8LN9QE      213830      2534.41 2018-09-26   35166    202780.26   296830.07  -205314.67         NaN    202780.26   296830.07  -205314.67         NaN
1527037     I8LN9QE      214106      2534.41 2018-09-27   35213    203376.19   297598.40  -205910.60         NaN    203376.19   297598.40  -205910.60         NaN
1574931     I8LN9QE      214364      2534.41 2018-09-28   35291    203027.76   295063.94  -205562.17         NaN    203027.76   295063.94  -205562.17         NaN
1622726     I8LN9QE      214726      2534.41 2018-10-01   35301    201269.15   294790.35  -203803.56         NaN    201269.15   294790.35  -203803.56         NaN
1670499     I8LN9QE      214836      2534.41 2018-10-02   35270    200247.37   293120.67  -202781.78         NaN    200247.37   293120.67  -202781.78         NaN
1718278     I8LN9QE      215154      2534.41 2018-10-03   35319    200407.09   293362.84  -202941.50         NaN    200407.09   293362.84  -202941.50         NaN
1766114     I8LN9QE      215531      2534.41 2018-10-04   35393    200009.18   292838.39  -202543.59         NaN    200009.18   292838.39  -202543.59         NaN
1814102     I8LN9QE      215849      2534.41 2018-10-05   35444    199159.74   291734.92  -201694.15         NaN    199159.74   291734.92  -201694.15         NaN
1862034     I8LN9QE      215837      2534.41 2018-10-08   35430    198846.04   291449.22  -201380.45         NaN    198846.04   291449.22  -201380.45         NaN
1909981     I8LN9QE      216064      2534.41 2018-10-09   35494    197852.25   289886.08  -200386.66         NaN    197852.25   289886.08  -200386.66         NaN
1958011     I8LN9QE      215991      2534.41 2018-10-10   35556    184444.43   291908.04  -184900.34         NaN    195622.03   286518.04  -198156.44         NaN
2006120     I8LN9QE      216193      2534.41 2018-10-11   35645    183650.95   291789.50  -184106.86         NaN    192488.10   281994.00  -195022.51         NaN
2054303     I8LN9QE      216573       455.91 2018-10-12   35693    186096.86   296347.23  -186552.77         NaN    186096.86   296347.23  -186552.77         NaN
2102477     I8LN9QE      217005      1475.16 2018-10-15   35644    188155.21   300964.73  -189630.37         NaN    188155.21   300964.73  -189630.37         NaN
2150673     I8LN9QE      217237      1475.16 2018-10-16   35767    185769.14   295137.34  -187244.30         NaN    185769.14   295137.34  -187244.30         NaN
2198966     I8LN9QE      217448      1475.16 2018-10-17   35854    186338.48   295904.25  -187813.64         NaN    186338.48   295904.25  -187813.64         NaN
2247347     I8LN9QE      218304      1475.16 2018-10-18   35937    184313.11   292725.00  -185788.27         NaN    184313.11   292725.00  -185788.27         NaN
2295817     I8LN9QE      218650      1475.16 2018-10-19   36036    180582.39   284796.70  -182057.55         NaN    180582.39   284796.70  -182057.55         NaN
2344715     I8LN9QE      219901      1475.16 2018-10-25   36364    170297.66   266104.80  -171772.82         NaN    170297.66   266104.80  -171772.82         NaN
2393622     I8LN9QE      220264      1475.16 2018-10-26   36456    169182.33   264275.62  -170657.49         NaN    169182.33   264275.62  -170657.49         NaN
2442670     I8LN9QE      221070      1475.16 2018-10-29   36570    164328.27   254555.82  -165803.43         NaN    164328.27   254555.82  -165803.43         NaN
2491800     I8LN9QE      221189      1475.16 2018-10-30   36662    166246.83   257486.33  -167721.99         NaN    166246.83   257486.33  -167721.99         NaN
2541011     I8LN9QE      221528      2312.66 2018-10-31   36732    170463.84   262787.77  -172776.50         NaN    170463.84   262787.77  -172776.50         NaN
2590198     I8LN9QE      221986      2312.66 2018-11-01   36622    168388.33   261222.75  -170700.99         NaN    168388.33   261222.75  -170700.99         NaN
2639152     I8LN9QE      222234      2312.66 2018-11-02   36491    167503.03   260699.18  -169815.69         NaN    167503.03   260699.18  -169815.69         NaN
2688040     I8LN9QE      222497      2312.66 2018-11-05   36539    168378.42   262511.89  -170691.08         NaN    168378.42   262511.89  -170691.08         NaN
2737024     I8LN9QE      222688      2312.66 2018-11-06   36635    169710.10   264933.71  -172022.76         NaN    169710.10   264933.71  -172022.76         NaN
2786092     I8LN9QE      223165      2312.66 2018-11-07   36726    171416.43   268061.90  -173729.09         NaN    171416.43   268061.90  -173729.09         NaN
2835282     I8LN9QE      223512      2312.66 2018-11-08   36775    169835.71   264628.73  -172148.37         NaN    169835.71   264628.73  -172148.37         NaN
2884516     I8LN9QE      223794      2312.66 2018-11-09   36832    166861.36   259055.08  -169174.02         NaN    166861.36   259055.08  -169174.02         NaN
2933736     I8LN9QE      223975      2312.66 2018-11-12   36842    163568.18   253298.68  -165880.84         NaN    163568.18   253298.68  -165880.84         NaN
2983026     I8LN9QE      224471      2312.66 2018-11-13   36936    163154.89   251943.54  -165467.55         NaN    163154.89   251943.54  -165467.55         NaN
3032400     I8LN9QE      224811      2312.66 2018-11-14   36993    160488.71   246918.58  -162801.37         NaN    160488.71   246918.58  -162801.37         NaN
3081894     I8LN9QE      225231      2378.08 2018-11-15   37084    167293.84   260240.34  -169671.92         NaN    167293.84   260240.34  -169671.92         NaN
3131428     I8LN9QE      225677      2378.08 2018-11-16   37144    163995.79   253862.98  -166373.87         NaN    163995.79   253862.98  -166373.87         NaN
3181083     I8LN9QE      226167      2378.08 2018-11-19   37253    161248.04   249399.63  -163626.12         NaN    161248.04   249399.63  -163626.12         NaN
3230853     I8LN9QE      226614      2378.08 2018-11-20   37366    159512.24   247059.63  -161890.32         NaN    159512.24   247059.63  -161890.32         NaN
3280744     I8LN9QE      227337      2378.08 2018-11-21   37492    161651.58   250094.54  -164029.66         NaN    161651.58   250094.54  -164029.66         NaN
3330710     I8LN9QE      227854      2378.08 2018-11-22   37551    160563.37   248504.80  -162941.45         NaN    160563.37   248504.80  -162941.45         NaN
3380845     I8LN9QE      228193      3284.58 2018-11-23   37659    161577.99   250379.26  -164862.57         NaN    161577.99   250379.26  -164862.57         NaN
3431047     I8LN9QE      228772      3284.58 2018-11-26   37791    161161.75   249389.64  -164446.33         NaN    161161.75   249389.64  -164446.33         NaN
3481355     I8LN9QE      229398      3284.58 2018-11-27   37880    162656.45   251928.64  -165941.03         NaN    162656.45   251928.64  -165941.03         NaN
3531802     I8LN9QE      230137      3284.58 2018-11-28   38027    167062.36   258683.08  -170346.94         NaN    167062.36   258683.08  -170346.94         NaN
3582344     I8LN9QE      230997      3284.58 2018-11-29   38146    165541.55   255709.92  -168826.13         NaN    165541.55   255709.92  -168826.13         NaN
3633129     I8LN9QE      231373      3284.58 2018-11-30   38304    165715.78   253370.54  -169000.36         NaN    165715.78   253370.54  -169000.36         NaN
3683735     I8LN9QE      232463      3284.58 2018-12-03   38191    163748.67   252084.25  -167033.25         NaN    163748.67   252084.25  -167033.25         NaN
3734205     I8LN9QE      233044      3284.58 2018-12-04   38125    160317.71   246145.59  -163602.29         NaN    160317.71   246145.59  -163602.29         NaN
3784709     I8LN9QE      233364      3284.58 2018-12-05   38205    159503.34   243879.76  -162787.92         NaN    159503.34   243879.76  -162787.92         NaN
3835330     I8LN9QE      234050      3284.58 2018-12-06   38338    158732.94   243973.91  -162017.52         NaN    158732.94   243973.91  -162017.52         NaN
3886128     I8LN9QE      234601      3284.58 2018-12-07   38450    157629.96   242988.37  -160914.54         NaN    157629.96   242988.37  -160914.54         NaN
3936970     I8LN9QE      234920      3284.58 2018-12-10   38546    156402.43   240555.90  -159687.01         NaN    156402.43   240555.90  -159687.01         NaN
3987993     I8LN9QE      235554      3284.58 2018-12-11   38711    157460.94   243056.78  -160745.52         NaN    157460.94   243056.78  -160745.52         NaN
4039132     I8LN9QE      235937      3284.58 2018-12-12   38812    157740.06   242960.80  -161024.64         NaN    157740.06   242960.80  -161024.64         NaN
4090374     I8LN9QE      236590      3284.58 2018-12-13   38922    156556.16   240339.94  -159840.74         NaN    156556.16   240339.94  -159840.74         NaN
4141902     I8LN9QE      237144      3284.58 2018-12-14   39108    155603.70   238640.57  -158888.28         NaN    155603.70   238640.57  -158888.28         NaN
4193674     I8LN9QE      237613      3284.58 2018-12-17   39407    153528.68   235176.39  -156813.26         NaN    153528.68   235176.39  -156813.26         NaN
4245663     I8LN9QE      238203      3284.58 2018-12-18   39559    153973.63   235674.75  -157258.21         NaN    153973.63   235674.75  -157258.21         NaN
4297720     I8LN9QE      238849      3284.58 2018-12-19   39627    151004.13   230691.47  -154288.71         NaN    151004.13   230691.47  -154288.71         NaN
4349825     I8LN9QE      239133      3284.58 2018-12-20   39680    149092.96   227165.79  -152377.54         NaN    149092.96   227165.79  -152377.54         NaN
4402097     I8LN9QE      239307      3284.58 2018-12-21   39771    146179.34   222404.63  -149463.92         NaN    146179.34   222404.63  -149463.92         NaN
4454418     I8LN9QE      239489      3284.58 2018-12-24   39875    146553.83   223822.61  -149838.41         NaN    146553.83   223822.61  -149838.41         NaN
4506728     I8LN9QE      239474      3284.58 2018-12-26   39860    151207.53   230730.71  -154492.11         NaN    151207.53   230730.71  -154492.11         NaN
4559111     I8LN9QE      239670      3284.58 2018-12-27   39930    149670.13   227848.76  -152954.71         NaN    149670.13   227848.76  -152954.71         NaN
4611593     I8LN9QE      239920      3284.58 2018-12-28   40049    151540.32   231688.32  -154824.90         NaN    151540.32   231688.32  -154824.90         NaN
4664169     I8LN9QE      240077      3284.58 2018-12-31   40078    151532.36   231006.37  -154816.94         NaN    151532.36   231006.37  -154816.94         NaN
4716602     I8LN9QE      240487    100917.27 2019-01-02   39985    220515.08   335467.26  -220865.35         NaN    153068.12   234902.46  -253985.39         NaN
4768960     I8LN9QE      240500    100917.27 2019-01-03   39919    217089.78   330853.25  -217440.05         NaN    149984.28   230830.25  -250901.55         NaN
4821342     I8LN9QE      240698       350.27 2019-01-04   39989    220607.99   336698.13  -220958.26         NaN    220607.99   336698.13  -220958.26         NaN
4873843     I8LN9QE      240952       350.27 2019-01-07   40074    220764.96   337474.09  -221115.23         NaN    220764.96   337474.09  -221115.23         NaN
4926473     I8LN9QE      241346       350.27 2019-01-08   40177    223796.47   340287.81  -224146.74         NaN    223796.47   340287.81  -224146.74         NaN
4979165     I8LN9QE      241583       350.27 2019-01-09   40287    228844.26   349113.23  -229194.53         NaN    228844.26   349113.23  -229194.53         NaN
5031931     I8LN9QE      241938       350.27 2019-01-10   40346    228527.42   350742.61  -228877.69         NaN    228527.42   350742.61  -228877.69         NaN
5084784     I8LN9QE      242205       350.27 2019-01-11   40428    229091.50   351437.14  -229441.77         NaN    229091.50   351437.14  -229441.77         NaN
5137754     I8LN9QE      242544       350.27 2019-01-14   40517    229403.73   352049.61  -229754.00         NaN    229403.73   352049.61  -229754.00         NaN
5190857     I8LN9QE      242861       350.27 2019-01-15   40586    229498.81   351597.02  -229849.08         NaN    229498.81   351597.02  -229849.08         NaN
5243803     I8LN9QE      243230       350.27 2019-01-16   40508    234862.04   357870.34  -235212.31         NaN    234862.04   357870.34  -235212.31         NaN
5296770     I8LN9QE      243667       350.27 2019-01-17   40597    237169.39   361371.99  -237519.66         NaN    237169.39   361371.99  -237519.66         NaN
5349774     I8LN9QE      243904       350.27 2019-01-18   40639    238579.55   363278.79  -238929.82         NaN    238579.55   363278.79  -238929.82         NaN
5402905     I8LN9QE      244083       350.27 2019-01-21   40688    242738.80   371079.13  -243089.07         NaN    242738.80   371079.13  -243089.07         NaN
5456062     I8LN9QE      244397       350.27 2019-01-22   40752    242649.49   371226.12  -242999.76         NaN    242649.49   371226.12  -242999.76         NaN
5509257     I8LN9QE      244686       350.27 2019-01-23   40807    240733.37   367799.66  -241083.64         NaN    240733.37   367799.66  -241083.64         NaN
5562496     I8LN9QE      244845       350.27 2019-01-24   40850    241474.31   368860.45  -241824.58         NaN    241474.31   368860.45  -241824.58         NaN
5615803     I8LN9QE      245151       350.27 2019-01-25   40912    242906.36   371299.66  -243256.63         NaN    242906.36   371299.66  -243256.63         NaN
5669232     I8LN9QE      245378       350.27 2019-01-28   40955    244586.40   374477.71  -244936.67         NaN    244586.40   374477.71  -244936.67         NaN
5722650     I8LN9QE      245654       350.27 2019-01-29   41027    244925.46   374392.65  -245275.73         NaN    244925.46   374392.65  -245275.73         NaN
5776142     I8LN9QE      245906       350.27 2019-01-30   41080    246327.83   376710.33  -246678.10         NaN    246327.83   376710.33  -246678.10         NaN
5829715     I8LN9QE      246305      1187.77 2019-01-31   41133    250057.52   383985.60  -251245.29         NaN    250057.52   383985.60  -251245.29         NaN
5883127     I8LN9QE      246618      1187.77 2019-02-01   40980    248703.70   381331.85  -249891.47         NaN    248703.70   381331.85  -249891.47         NaN
5936354     I8LN9QE      246664      1187.77 2019-02-04   40825    251075.45   385434.36  -252263.22         NaN    251075.45   385434.36  -252263.22         NaN
5989530     I8LN9QE      247173      1187.77 2019-02-05   40879    253016.82   388538.03  -254204.59         NaN    253016.82   388538.03  -254204.59         NaN
6042755     I8LN9QE      247441      1187.77 2019-02-06   40919    252071.00   386412.01  -253258.77         NaN    252071.00   386412.01  -253258.77         NaN

# BV399 (BOOK VALUE)

1.   bv399_security_book_val.csv
2.   bv399_account_book_val.csv

## bv399_security_book_val.csv

* 11114098 rows and 10 columns
* 61116 accounts
* trading dates range from 2018-08-13 to 2019-08-12         ---> 254 trading days

         account_id fgn_ctt_ind   fi_id  file_date    pos_bv  pos_cos_qty pos_sus_ind     pro_dte rsp_elg_ind  seq_id
1451538     I8LN9QE           Y  033740 2018-10-10  12719.36           80         NaN  2017-08-17           Y   18265
1451539     I8LN9QE           N  070623 2018-10-10      0.00            0         NaN  2018-10-10           Y   18266
1451540     I8LN9QE           N  14439H 2018-10-10  71515.00         5900         NaN  2018-10-10           Y   18267
1451541     I8LN9QE           N  28843F 2018-10-10   6305.00        16000         NaN  2017-01-17           Y   18268
1451542     I8LN9QE           N  591131 2018-10-10  69297.50          925         NaN  2017-08-24           Y   18269
1451543     I8LN9QE           N  66908B 2018-10-10   4290.00         1100         NaN  2018-06-21           Y   18270
1451544     I8LN9QE           N  671835 2018-10-10  68419.00         1250         NaN  2017-10-31           Y   18271
1451545     I8LN9QE           N  91661P 2018-10-10      0.00        20000         NaN  2017-06-30           Y   18272
1451546     I8LN9QE           N  91661S 2018-10-10   4200.00        30000         NaN  2017-12-05           Y   18273
1451547     I8LN9QE           N  91661T 2018-10-10   5610.00        33000         NaN  2018-04-11           Y   18274
1496912     I8LN9QE           Y  033740 2018-10-12  12719.36           80         NaN  2017-08-17           Y   20180
1496913     I8LN9QE           N  070623 2018-10-12      0.00            0         NaN  2018-10-12           Y   20181
1496914     I8LN9QE           N  14439H 2018-10-12  71515.00         5900         NaN  2018-10-10           Y   20182
1496915     I8LN9QE           N  28843F 2018-10-12   6305.00        16000         NaN  2017-01-17           Y   20183
1496916     I8LN9QE           N  591131 2018-10-12  69297.50          925         NaN  2017-08-24           Y   20184
1496917     I8LN9QE           N  66908B 2018-10-12   4290.00         1100         NaN  2018-06-21           Y   20185
1496918     I8LN9QE           N  671835 2018-10-12  68419.00         1250         NaN  2017-10-31           Y   20186
1496919     I8LN9QE           N  91661P 2018-10-12      0.00        20000         NaN  2017-06-30           Y   20187
1496920     I8LN9QE           N  91661S 2018-10-12   4200.00        30000         NaN  2017-12-05           Y   20188
1496921     I8LN9QE           N  91661T 2018-10-12   5610.00        33000         NaN  2018-04-11           Y   20189
3981035     I8LN9QE           Y  033740 2019-01-02  12719.36           80         NaN  2017-08-17           Y   63260
3981036     I8LN9QE           N  118224 2019-01-02  85847.00          840         NaN  2019-01-02           Y   63261
3981037     I8LN9QE           N  14439H 2019-01-02  86235.00         8000         NaN  2019-01-02           Y   63262
3981038     I8LN9QE           N  28843F 2019-01-02   6305.00        16000         NaN  2017-01-17           Y   63263
3981039     I8LN9QE           N  591131 2019-01-02  69297.50          925         NaN  2017-08-24           Y   63264
3981040     I8LN9QE           N  66908B 2019-01-02   4290.00         1100         NaN  2018-06-21           Y   63265
3981041     I8LN9QE           N  671835 2019-01-02  68419.00         1250         NaN  2017-10-31           Y   63266
3981042     I8LN9QE           N  91661P 2019-01-02      0.00        20000         NaN  2017-06-30           Y   63267
3981043     I8LN9QE           N  91661S 2019-01-02   4200.00        30000         NaN  2017-12-05           Y   63268
3981044     I8LN9QE           N  91661T 2019-01-02   5610.00        33000         NaN  2018-04-11           Y   63269
4105958     I8LN9QE           Y  033740 2019-01-04  12719.36           80         NaN  2017-08-17           Y   14187
4105959     I8LN9QE           N  118224 2019-01-04  85847.00          840         NaN  2019-01-02           Y   14188
4105960     I8LN9QE           N  14439H 2019-01-04  86235.00         8000         NaN  2019-01-02           Y   14189
4105961     I8LN9QE           N  28843F 2019-01-04   6305.00        16000         NaN  2017-01-17           Y   14190
4105962     I8LN9QE           N  591131 2019-01-04  69297.50          925         NaN  2017-08-24           Y   14191
4105963     I8LN9QE           N  66908B 2019-01-04   4290.00         1100         NaN  2018-06-21           Y   14192
4105964     I8LN9QE           N  671835 2019-01-04  68419.00         1250         NaN  2017-10-31           Y   14193
4105965     I8LN9QE           N  91661P 2019-01-04      0.00        20000         NaN  2017-06-30           Y   14194
4105966     I8LN9QE           N  91661S 2019-01-04   4200.00        30000         NaN  2017-12-05           Y   14195
4105967     I8LN9QE           N  91661T 2019-01-04   5610.00        33000         NaN  2018-04-11           Y   14196
5826493     I8LN9QE           Y  033740 2019-02-28  12719.36           80         NaN  2017-08-17           Y   19904
5826494     I8LN9QE           N  118224 2019-02-28  85847.00          840         NaN  2019-01-02           Y   19905
5826495     I8LN9QE           N  14439H 2019-02-28  61442.44         5700         NaN  2019-02-28           Y   19906
5826496     I8LN9QE           N  28843F 2019-02-28   6305.00        16000         NaN  2017-01-17           Y   19907
5826497     I8LN9QE           N  591131 2019-02-28  69297.50          925         NaN  2017-08-24           Y   19908
5826498     I8LN9QE           N  66908B 2019-02-28   4290.00         1100         NaN  2018-06-21           Y   19909
5826499     I8LN9QE           N  671835 2019-02-28  68419.00         1250         NaN  2017-10-31           Y   19910
5826500     I8LN9QE           N  91661P 2019-02-28      0.00        20000         NaN  2017-06-30           Y   19911
5826501     I8LN9QE           N  91661S 2019-02-28   4200.00        30000         NaN  2017-12-05           Y   19912
5826502     I8LN9QE           N  91661T 2019-02-28   5610.00        33000         NaN  2018-04-11           Y   19913
6137728     I8LN9QE           Y  033740 2019-03-11  12719.36           80         NaN  2017-08-17           Y   20176
6137729     I8LN9QE           N  118224 2019-03-11  85847.00          840         NaN  2019-01-02           Y   20177
6137730     I8LN9QE           N  14439H 2019-03-11  61442.44         5700         NaN  2019-02-28           Y   20178
6137731     I8LN9QE           N  28843F 2019-03-11   6305.00        16000         NaN  2017-01-17           Y   20179
6137732     I8LN9QE           N  591131 2019-03-11  69297.50          925         NaN  2017-08-24           Y   20180
6137733     I8LN9QE           N  66908B 2019-03-11    390.00          100         NaN  2019-03-11           Y   20181
6137734     I8LN9QE           N  671835 2019-03-11  68419.00         1250         NaN  2017-10-31           Y   20182
6137735     I8LN9QE           N  91661P 2019-03-11      0.00        20000         NaN  2017-06-30           Y   20183
6137736     I8LN9QE           N  91661S 2019-03-11   4200.00        30000         NaN  2017-12-05           Y   20184
6137737     I8LN9QE           N  91661T 2019-03-11   5610.00        33000         NaN  2018-04-11           Y   20185
6174592     I8LN9QE           Y  033740 2019-03-12  12719.36           80         NaN  2017-08-17           Y   29359
6174593     I8LN9QE           N  118224 2019-03-12  85847.00          840         NaN  2019-01-02           Y   29360
6174594     I8LN9QE           N  14439H 2019-03-12  61442.44         5700         NaN  2019-02-28           Y   29361
6174595     I8LN9QE           N  28843F 2019-03-12   6305.00        16000         NaN  2017-01-17           Y   29362
6174596     I8LN9QE           N  591131 2019-03-12  69297.50          925         NaN  2017-08-24           Y   29363
6174597     I8LN9QE           N  66908B 2019-03-12    390.00          100         NaN  2019-03-11           Y   29364
6174598     I8LN9QE           N  671835 2019-03-12  68419.00         1250         NaN  2017-10-31           Y   29365
6174599     I8LN9QE           N  91661P 2019-03-12      0.00        20000         NaN  2017-06-30           Y   29366
6174600     I8LN9QE           N  91661S 2019-03-12   4200.00        30000         NaN  2017-12-05           Y   29367
6174601     I8LN9QE           N  91661T 2019-03-12   5610.00        33000         NaN  2018-04-11           Y   29368
6546525     I8LN9QE           Y  033740 2019-03-20  12719.36           80         NaN  2017-08-17           Y   10988
6546526     I8LN9QE           N  118224 2019-03-20  85847.00          840         NaN  2019-01-02           Y   10989
6546527     I8LN9QE           N  14439H 2019-03-20  61442.44         5700         NaN  2019-02-28           Y   10990
6546528     I8LN9QE           N  28843F 2019-03-20   6305.00        16000         NaN  2017-01-17           Y   10991
6546529     I8LN9QE           N  591131 2019-03-20  69297.50          925         NaN  2017-08-24           Y   10992
6546530     I8LN9QE           N  66908B 2019-03-20   4947.36         1100         NaN  2019-03-20           Y   10993
6546531     I8LN9QE           N  671835 2019-03-20  68419.00         1250         NaN  2017-10-31           Y   10994
6546532     I8LN9QE           N  91661P 2019-03-20      0.00        20000         NaN  2017-06-30           Y   10995
6546533     I8LN9QE           N  91661S 2019-03-20   4200.00        30000         NaN  2017-12-05           Y   10996
6546534     I8LN9QE           N  91661T 2019-03-20   5610.00        33000         NaN  2018-04-11           Y   10997
6567566     I8LN9QE           Y  033740 2019-03-21  12719.36           80         NaN  2017-08-17           Y   17720
6567567     I8LN9QE           N  118224 2019-03-21  85847.00          840         NaN  2019-01-02           Y   17721
6567568     I8LN9QE           N  14439H 2019-03-21  61442.44         5700         NaN  2019-02-28           Y   17722
6567569     I8LN9QE           N  28843F 2019-03-21   6305.00        16000         NaN  2017-01-17           Y   17723
6567570     I8LN9QE           N  591131 2019-03-21  69297.50          925         NaN  2017-08-24           Y   17724
6567571     I8LN9QE           N  66908B 2019-03-21   4947.36         1100         NaN  2019-03-20           Y   17725
6567572     I8LN9QE           N  671835 2019-03-21  68419.00         1250         NaN  2017-10-31           Y   17726
6567573     I8LN9QE           N  91661P 2019-03-21      0.00        20000         NaN  2017-06-30           Y   17727
6567574     I8LN9QE           N  91661S 2019-03-21   4200.00        30000         NaN  2017-12-05           Y   17728
6567575     I8LN9QE           N  91661T 2019-03-21   5610.00        33000         NaN  2018-04-11           Y   17729
6567576     I8LN9QE           N  91661X 2019-03-21      0.00         1000         INV  2019-03-21           Y   17730
9248065     I8LN9QE           Y  033740 2019-06-14  12719.36           80         NaN  2017-08-17           Y  119891
9248066     I8LN9QE           N  118224 2019-06-14  85847.00          840         NaN  2019-01-02           Y  119892
9248067     I8LN9QE           N  14439H 2019-06-14  94467.44        10700         NaN  2019-06-14           Y  119893
9248068     I8LN9QE           N  28843F 2019-06-14   6305.00        16000         NaN  2017-01-17           Y  119894
9248069     I8LN9QE           N  591131 2019-06-14  69297.50          925         NaN  2017-08-24           Y  119895
9248070     I8LN9QE           N  66908B 2019-06-14   4947.36         1100         NaN  2019-03-20           Y  119896
9248071     I8LN9QE           N  671835 2019-06-14  68419.00         1250         NaN  2017-10-31           Y  119897
9248072     I8LN9QE           N  91661P 2019-06-14      0.00        20000         NaN  2017-06-30           Y  119898
9248073     I8LN9QE           N  91661S 2019-06-14   4200.00        30000         NaN  2017-12-05           Y  119899
9248074     I8LN9QE           N  91661T 2019-06-14   5610.00        33000         NaN  2018-04-11           Y  119900
9248075     I8LN9QE           N  91661X 2019-06-14      0.00         1000         INV  2019-03-21           Y  119901
9476219     I8LN9QE           Y  033740 2019-06-18  12719.36           80         NaN  2017-08-17           Y   44956
9476220     I8LN9QE           N  118224 2019-06-18  85847.00          840         NaN  2019-01-02           Y   44957
9476221     I8LN9QE           N  14439H 2019-06-18  94467.44        10700         NaN  2019-06-14           Y   44958
9476222     I8LN9QE           N  28843F 2019-06-18   6305.00        16000         NaN  2017-01-17           Y   44959
9476223     I8LN9QE           N  591131 2019-06-18  69297.50          925         NaN  2017-08-24           Y   44960
9476224     I8LN9QE           N  66908B 2019-06-18   4947.36         1100         NaN  2019-03-20           Y   44961
9476225     I8LN9QE           N  671835 2019-06-18  68419.00         1250         NaN  2017-10-31           Y   44962
9476226     I8LN9QE           N  91661P 2019-06-18      0.00        20000         NaN  2017-06-30           Y   44963
9476227     I8LN9QE           N  91661S 2019-06-18   4200.00        30000         NaN  2017-12-05           Y   44964
9476228     I8LN9QE           N  91661T 2019-06-18   5610.00        33000         NaN  2018-04-11           Y   44965
9476229     I8LN9QE           N  91661X 2019-06-18      0.00         1000         INV  2019-03-21           Y   44966
10495245    I8LN9QE           Y  033740 2019-07-19  12719.36           80         NaN  2017-08-17           Y   25434
10495246    I8LN9QE           N  118224 2019-07-19  85847.00          840         NaN  2019-01-02           Y   25435
10495247    I8LN9QE           N  14439H 2019-07-19  94467.44        10700         NaN  2019-06-14           Y   25436
10495248    I8LN9QE           N  28843F 2019-07-19   6305.00        16000         NaN  2017-01-17           Y   25437
10495249    I8LN9QE           N  591131 2019-07-19  69297.50          925         NaN  2017-08-24           Y   25438
10495250    I8LN9QE           N  66908B 2019-07-19   4947.36         1100         NaN  2019-03-20           Y   25439
10495251    I8LN9QE           N  671835 2019-07-19  68419.00         1250         NaN  2017-10-31           Y   25440
10495252    I8LN9QE           N  91661P 2019-07-19      0.00        20000         NaN  2017-06-30           Y   25441
10495253    I8LN9QE           N  91661S 2019-07-19   4200.00        30000         NaN  2017-12-05           Y   25442
10495254    I8LN9QE           N  91661T 2019-07-19   5610.00        33000         NaN  2018-04-11           Y   25443
10495255    I8LN9QE           N  91661X 2019-07-19      0.00         1000         INV  2019-03-21           Y   25444
3461669     I8LN9QF           Y  01442A 2018-12-19   6541.00          100         NaN  2017-09-29           Y   51438
3461670     I8LN9QF           Y  033740 2018-12-19  25691.64          212         NaN  2017-08-17           Y   51439
3461671     I8LN9QF           Y  257440 2018-12-19      0.00            0         NaN  2018-12-19           Y   51440
3598297     I8LN9QF           Y  01442A 2018-12-21   6541.00          100         NaN  2017-09-29           Y   42506
3598298     I8LN9QF           Y  033740 2018-12-21  25691.64          212         NaN  2017-08-17           Y   42507
3598299     I8LN9QF           Y  257440 2018-12-21      0.00            0         NaN  2018-12-21           Y   42508
3981045     I8LN9QF           Y  01442A 2019-01-02   6541.00          100         NaN  2017-09-29           Y   63270
3981046     I8LN9QF           Y  033740 2019-01-02  25691.64          212         NaN  2017-08-17           Y   63271
3981047     I8LN9QF           Y  257440 2019-01-02      0.00            0         NaN  2018-12-21           Y   63272
846424      I8LN9QS           N  075695 2018-09-17  24836.00         4000         NaN  2018-01-31           Y  130045
846425      I8LN9QS           N  118224 2018-09-17  40212.00          400         NaN  2017-10-27           Y  130046
846426      I8LN9QS           N  28843F 2018-09-17  18445.00        26500         NaN  2017-01-03           Y  130047
846427      I8LN9QS           N  46811H 2018-09-17  14600.00        30000         NaN  2018-07-31           Y  130048
3235139     I8LN9QS           N  075695 2018-12-17  24836.00         4000         NaN  2018-01-31           Y  117380
3235140     I8LN9QS           N  118224 2018-12-17  40212.00          400         NaN  2017-10-27           Y  117381
3235141     I8LN9QS           N  28843F 2018-12-17  18445.00        26500         NaN  2017-01-03           Y  117382
3235142     I8LN9QS           N  46811H 2018-12-17  14600.00        30000         NaN  2018-07-31           Y  117383
3981048     I8LN9QS           N  075695 2019-01-02  24836.00         4000         NaN  2018-01-31           Y   63273
3981049     I8LN9QS           N  118224 2019-01-02  59713.20          590         NaN  2019-01-02           Y   63274
3981050     I8LN9QS           N  28843F 2019-01-02  18445.00        26500         NaN  2017-01-03           Y   63275
3981051     I8LN9QS           N  46811H 2019-01-02  14600.00        30000         NaN  2018-07-31           Y   63276
4105968     I8LN9QS           N  075695 2019-01-04  24836.00         4000         NaN  2018-01-31           Y   14197
4105969     I8LN9QS           N  118224 2019-01-04  59713.20          590         NaN  2019-01-02           Y   14198
4105970     I8LN9QS           N  28843F 2019-01-04  18445.00        26500         NaN  2017-01-03           Y   14199
4105971     I8LN9QS           N  46811H 2019-01-04  14600.00        30000         NaN  2018-07-31           Y   14200
5826503     I8LN9QS           N  075695 2019-02-28  24836.00         4000         NaN  2018-01-31           Y   19914
5826504     I8LN9QS           N  118224 2019-02-28  59713.20          590         NaN  2019-01-02           Y   19915
5826505     I8LN9QS           N  14439H 2019-02-28  28152.00         2300         NaN  2019-02-28           Y   19916
5826506     I8LN9QS           N  28843F 2019-02-28  18445.00        26500         NaN  2017-01-03           Y   19917
5826507     I8LN9QS           N  46811H 2019-02-28  14600.00        30000         NaN  2018-07-31           Y   19918
6404352     I8LN9QS           N  075695 2019-03-15  24836.00         4000         NaN  2018-01-31           Y  150413
6404353     I8LN9QS           N  118224 2019-03-15  59713.20          590         NaN  2019-01-02           Y  150414
6404354     I8LN9QS           N  14439H 2019-03-15  28152.00         2300         NaN  2019-02-28           Y  150415
6404355     I8LN9QS           N  28843F 2019-03-15  18445.00        26500         NaN  2017-01-03           Y  150416
6404356     I8LN9QS           N  46811H 2019-03-15  14600.00        30000         NaN  2018-07-31           Y  150417
8717876     I8LN9QS           N  075695 2019-05-31  24836.00         4000         NaN  2018-01-31           Y   17692
8717877     I8LN9QS           N  118224 2019-05-31  59713.20          590         NaN  2019-01-02           Y   17693
8717878     I8LN9QS           N  14439H 2019-05-31  28152.00         2300         NaN  2019-02-28           Y   17694
8717879     I8LN9QS           N  28843F 2019-05-31  18445.00        26500         NaN  2017-01-03           Y   17695
8717880     I8LN9QS           N  32082F 2019-05-31  14600.00         1899         NaN  2019-05-31           Y   17696
8717881     I8LN9QS           N  46811H 2019-05-31      0.00            0         NaN  2019-05-31           Y   17697
9006405     I8LN9QS           N  075695 2019-06-07  24836.00         4000         NaN  2018-01-31           Y   17663
9006406     I8LN9QS           N  118224 2019-06-07  59713.20          590         NaN  2019-01-02           Y   17664
9006407     I8LN9QS           N  14439H 2019-06-07  28152.00         2300         NaN  2019-02-28           Y   17665

## bv399_account_book_val.csv

* 1810848 rows and 9 columns
* 67604 accounts
* trading dates range from 2018-08-13 to 2019-08-12         ---> 254 trading days

        account_id  act_bv_amt  act_csh_amt  act_fgn_pct  act_fgn_pct.1  file_date plan_id rep_code  seq_id
243440     I8LN9QE   242811.77       455.91          NaN            NaN 2018-10-10     NaN     0RC2    3061
250798     I8LN9QE   242811.77       455.91          NaN            NaN 2018-10-12     NaN     0RC2    3429
653359     I8LN9QE   343273.13       350.27          NaN            NaN 2019-01-02     NaN     0RC2    9093
673166     I8LN9QE   343273.13       350.27          NaN            NaN 2019-01-04     NaN     0RC2    2517
949876     I8LN9QE   318442.56       312.26          NaN            NaN 2019-02-28     NaN     0RC2    3045
997895     I8LN9QE   319147.56      4917.26          NaN            NaN 2019-03-11     NaN     0RC2    2892
1004100    I8LN9QE   319147.56      4917.26          NaN            NaN 2019-03-12     NaN     0RC2    4943
1071106    I8LN9QE   319147.56       359.90          NaN            NaN 2019-03-20     NaN     0RC2    1918
1074859    I8LN9QE   319147.56       359.90          NaN            NaN 2019-03-21     NaN     0RC2    3141
1501814    I8LN9QE   322262.31    -29550.35          NaN            NaN 2019-06-14     NaN     0RC2   22714
1541493    I8LN9QE   322262.31    -29550.35          NaN            NaN 2019-06-18     NaN     0RC2    7018
1713921    I8LN9QE   322104.76    -29707.90          NaN            NaN 2019-07-19     NaN     0RC2    4641
570210     I8LN9QF   104429.37     72196.73          NaN            NaN 2018-12-19     NaN     0RC2    7782
593805     I8LN9QF   104429.37     72196.73          NaN            NaN 2018-12-21     NaN     0RC2    7200
653360     I8LN9QF    32232.64         0.00          NaN            NaN 2019-01-02     NaN     0RC2    9094
146020     I8LN9QS   117048.15     18955.15          NaN            NaN 2018-09-17      RS     0RC2   24899
531734     I8LN9QS   117649.77     19556.77          NaN            NaN 2018-12-17      RS     0RC2   21524
653361     I8LN9QS   117749.77       155.57          NaN            NaN 2019-01-02      RS     0RC2    9095
673167     I8LN9QS   117749.77       155.57          NaN            NaN 2019-01-04      RS     0RC2    2518
949877     I8LN9QS   148293.77      2547.57          NaN            NaN 2019-02-28      RS     0RC2    3046
1047741    I8LN9QS   148251.39      2505.19          NaN            NaN 2019-03-15      RS     0RC2   28977
1411467    I8LN9QS   149182.39      3436.19          NaN            NaN 2019-05-31      RS     0RC2    2735
1457347    I8LN9QS   149182.39      3441.33          NaN            NaN 2019-06-07      RS     0RC2    2961
1501815    I8LN9QS   149140.01      3398.95          NaN            NaN 2019-06-14      RS     0RC2   22715